# Shared prompt blocks for round 2 (sourced by the run scripts). Written canon only; see ../README.md.
cd "D:/Final Fantasy"
S=D:/Tools/pyrefly-art-backup/candidates/2026-09-27-ff7/round2-sketches
C=D:/Tools/pyrefly-art-backup/candidates/2026-09-27-ff7
waitq() { while [ "$(curl -s http://127.0.0.1:8188/queue | python -c 'import json,sys;d=json.load(sys.stdin);print(len(d["queue_pending"]))')" -ge 2 ]; do sleep 15; done; }
GT="no humans, robot, mecha, (mechanical scorpion:1.3), giant security robot, final fantasy vii, heavy and imposing boss, (huge bulky armored body:1.2), massive tall red armored shell, thick mechanical legs planted wide, segmented scorpion tail, (laser cannon at the tail tip:1.3), (big round glowing lens on the tail tip:1.2), twin gun barrels under the head, head with one round sensor eye, grey disc on its back, red armor panels with dark grey steel joints and hydraulic pistons, detailed mechanical parts, (red armor:1.2)"
GN="1girl, 1boy, human, person, pilot, cockpit, humanoid, bipedal, arms, hands, holding weapon, gundam, real scorpion, insect, animal, building, floor, ground, rivets, grainy, flat colors, toy, stinger, blade, spike, claw, hook, sickle"
gs() { waitq; node tools/gen/comfy.mjs boss --name ff7-guard-scorpion --nonBiped --facing right --size 1216x832 --tags "$GT$4" --negAdd "$GN" --img2img "$S/$1" --denoise $2 --pose $3 --out $C/guard-scorpion/round2/$3.png --batch $5 2>&1 | grep -E "\->|FAIL|black|rror|reject"; }
BT="1boy, barret wallace, final fantasy vii, safe, solo, male focus, dark-skinned male, very muscular, large heavy-set build, hi-top fade haircut, thick black beard, (gun arm:1.3), (right forearm replaced by a mechanical gatling gun:1.2), no right hand, dirty brown vest, bare muscular arms, metal bands on the left forearm, metal bands around the waist, two dog tags, skull tattoo on left shoulder, silver hoop earring, green pants, large brown boots"
BN="sunglasses, holding gun, holding weapon, two guns, hand on gun, gun in hand"
br() { waitq; node tools/gen/comfy.mjs character --name ff7-barret --facing left --tags "$BT" --negAdd "$BN" --img2img "$S/barret2.png" --denoise $1 --pose $2 --poseTags "fighting stance, gun arm held forward and aimed ahead, left fist clenched, determined, looking at viewer" --out $C/barret/round2/$2.png --batch $3 2>&1 | grep -E "\->|FAIL|black|rror|reject"; }
CT="1boy, cloud strife, final fantasy vii, safe, solo, male focus, spiky blonde hair, blue eyes, sleeveless dark indigo shirt, (single metal pauldron on his left shoulder only:1.2), bare right shoulder, two brown leather belts at the waist, dark indigo baggy pants, brown boots, brown gloves, gear-shaped metal armlet on the left forearm, wristband on the right wrist, buster sword, (huge broadsword:1.2), wide heavy blade"
cl() { waitq; node tools/gen/comfy.mjs character --name ff7-cloud --facing left --tags "$CT" --img2img "$S/${4:-cloud2.png}" --denoise $1 --pose $2 --poseTags "fighting stance, holding the huge broadsword in both hands, blade angled down in front, stoic expression, ${5:-looking at viewer}" --out $C/cloud/round2/$2.png --batch $3 2>&1 | grep -E "\->|FAIL|black|rror|reject"; }
