#!/usr/bin/env node
/**
 * Writes the "Direction B, the whole score" section of docs/audio/audition.html
 * between the `direction-b:begin` / `direction-b:end` markers (inserted at the
 * top of the page the first time), from docs/audio/direction-b-2026-09-27.json
 * and the candidate manifest. Re-run it rather than editing the section by hand.
 *
 *   node tools/audio/modern/audition-b-score.mjs
 *
 * Game case: both (every cue of both games; the per-cue game is shown).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const PAGE = path.join(ROOT, 'docs/audio/audition.html');
const report = JSON.parse(readFileSync(path.join(ROOT, 'docs/audio/direction-b-2026-09-27.json'), 'utf8'));
const qaFile = path.join(ROOT, 'docs/audio/direction-b-2026-09-27-qa.json');
const qa = existsSync(qaFile) ? JSON.parse(readFileSync(qaFile, 'utf8')) : null;
const qaRow = (name) => qa?.cues?.find((c) => c.name === name);

const CAND = '../../public/audio/candidates/direction-b-2026-09-27';
const SKETCH = '../../public/audio/candidates/direction-b-sketches-2026-09-27';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const mmss = (s) => `${Math.floor(s / 60)}:${(s % 60).toFixed(0).padStart(2, '0')}`;
const GAME = { ffx: 'FFX', ffx2: 'FFX-2', both: 'Both games' };
const FOUR = ['title', 'boss-seymour', 'boss-shuyin', 'boss-yojimbo'];

function stats(name, c) {
  const q = qaRow(name);
  const m = c.takes?.find((t) => t.stem === c.pick)?.measure ?? {};
  const bits = [
    mmss(c.duration), `loops ${mmss(c.loopStart)}&ndash;${mmss(c.loopEnd)}`,
    `${c.finish.lufs.toFixed(1)} LUFS`, `${c.finish.truePeakDb.toFixed(1)} dBTP`,
    `LRA ${c.lra ?? '-'} LU`, `take ${esc(c.pick.replace(/^B-.*-d(\d+)-s(\d+)$/, 'strength 0.$1, seed $2'))}`,
    `structure kept ${m.structureFidelity ?? '-'}`,
  ];
  if (q) bits.push(q.failures.length ? `QA: ${q.failures.length} finding(s)` : 'QA: all gates pass');
  if (c.flagged) bits.push('FLAGGED: tempo moved');
  return `<p class="stats">${bits.map((b) => `<span>${b}</span>`).join('')}</p>`;
}

function article(name, c, withToday) {
  const today = withToday
    ? `  <p class="blurb" style="margin:8px 0 2px">Today</p>\n  <audio controls preload="none" src="../../public/audio/music/${name}.mp3"></audio>\n  <p class="blurb" style="margin:8px 0 2px">Direction B</p>\n`
    : '';
  return `<article class="cue">
  <h4>${esc(name)}</h4>
  <p class="blurb">${esc(c.plays)}. ${GAME[c.game]}; ${esc(c.key)}, ${c.bpm} bpm, ${esc(c.meter)}.</p>
${today}  <audio controls preload="none" src="${CAND}/${name}.mp3"></audio>
  ${stats(name, c)}
</article>`;
}

const cues = Object.entries(report.cues).filter(([, c]) => !c.failed);
const failed = Object.entries(report.cues).filter(([, c]) => c.failed);
const four = FOUR.filter((n) => report.cues[n] && !report.cues[n].failed).map((n) => article(n, report.cues[n], true));
const rest = cues.filter(([n]) => !FOUR.includes(n)).map(([n, c]) => article(n, c, false));
const sketches = Object.entries(report.sketches ?? {}).filter(([, s]) => !s.failed).map(([k, s]) => `<article class="cue">
  <h4>Macalania scene sketch ${k.slice(-1).toUpperCase()} in Direction B</h4>
  <p class="blurb">The 24 September sketch (<a href="${esc(path.relative(path.join(ROOT, 'docs/audio'), path.join(ROOT, s.source)).replaceAll('\\', '/'))}">as you heard it</a>), restyled the same way. FFX only.</p>
  <audio controls preload="none" src="${SKETCH}/${path.basename(s.file)}"></audio>
  <p class="stats"><span>${s.finish.lufs.toFixed(1)} LUFS</span><span>${s.finish.truePeakDb.toFixed(1)} dBTP</span><span>take ${esc(s.pick.replace(/^B-.*-d(\d+)-s(\d+)$/, 'strength 0.$1, seed $2'))}</span>${s.flagged ? '<span>FLAGGED: tempo moved</span>' : ''}</p>
</article>`);

const section = `<!-- direction-b:begin — generated by tools/audio/modern/audition-b-score.mjs from docs/audio/direction-b-2026-09-27.json. Re-run it instead of editing by hand. -->
<h2 style="margin-top:0">Direction B, the whole score (new, 27 September)</h2>
<p class="group-note">
  <strong>You picked Direction B</strong> (track 7 of the 26 September pack: the AI restyle). This is every music cue in the game made that way:
  the same model and settings as the clip you picked, fed today&rsquo;s recording of each cue, so the notes, the tempo and the form stay and the
  sound and the playing change. Each cue loops at the same points as today (the join is crossfaded so it should not be heard), and each is levelled
  to &minus;16 LUFS like the game&rsquo;s music. <strong>These are candidates: nothing in the game has changed.</strong>
  <strong>I cannot hear any of this.</strong> Every number is a measurement; &ldquo;structure kept&rdquo; is how much of the score&rsquo;s rhythm and
  harmony the restyle kept (0.85 is the most this measure can give; your clip scored 0.63).
  ${failed.length ? `Not rendered: ${failed.map(([n, c]) => `${esc(n)} (${esc(c.failed)})`).join('; ')}.` : ''}
</p>

<h3>The four you said sound like SNES music: today, then Direction B</h3>
${four.join('\n\n')}

${sketches.length ? `<h3>Macalania: the three scene sketches in Direction B</h3>\n${sketches.join('\n\n')}\n` : ''}
<div class="check">
  <p style="margin-top:0"><strong>Three questions.</strong> Answer what you like; the button only writes the text into the box.</p>
  <p class="score"><label>1. Good enough to ship? (all / which not) <input type="text" size="30" data-direction-b="Good enough to ship"></label></p>
  <p class="score"><label>2. The new sound, out of 10 <input type="number" min="1" max="10" step="1" data-direction-b="New sound"></label></p>
  <p class="score"><label>3. Macalania: A, B or C <input type="text" size="4" data-direction-b="Macalania"></label></p>
  <p><button type="button" id="direction-b-collect" style="font:inherit;padding:8px 16px;cursor:pointer;color:var(--paper);background:var(--gold);border:0;border-radius:6px">Collect my answers</button></p>
  <textarea id="direction-b-out" rows="5" style="width:100%;font:12px/1.5 ui-monospace,Menlo,Consolas,monospace;color:var(--ink);background:var(--paper);border:1px solid var(--rule);border-radius:6px;padding:10px" readonly placeholder="Your answers appear here."></textarea>
</div>
<script>
  document.getElementById('direction-b-collect').addEventListener('click', function () {
    var lines = ['Pyrefly Reprise — Direction B, whole score, 2026-09-27', ''];
    document.querySelectorAll('input[data-direction-b]').forEach(function (input) {
      var v = input.value.trim();
      lines.push(input.dataset.directionB + ': ' + (v === '' ? '(not answered)' : input.type === 'number' ? v + '/10' : v));
    });
    document.getElementById('direction-b-out').value = lines.join('\\n');
  });
</script>

<h3>Every other cue in Direction B</h3>
${rest.join('\n\n')}
<!-- direction-b:end -->`;

let html = readFileSync(PAGE, 'utf8');
const begin = html.indexOf('<!-- direction-b:begin');
const endTag = '<!-- direction-b:end -->';
if (begin >= 0) {
  const end = html.indexOf(endTag, begin);
  html = html.slice(0, begin) + section + html.slice(end + endTag.length);
} else {
  const anchor = html.indexOf('<!-- macalania-scene:begin');
  html = html.slice(0, anchor) + section + '\n\n' + html.slice(anchor);
}
writeFileSync(PAGE, html);
process.stderr.write(`[audition] Direction B section: ${cues.length} cues, ${sketches.length} sketches\n`);
