/**
 * Alias table: the `sfxKey` names ability data was authored with, mapped onto
 * real cues in the bank.
 *
 * The FFX ability, aeon and item data names its sounds per ability
 * (`sfx-fira-cast`, `sfx-item-heal-medium`, `sfx-wakka-shot-ice`), while the
 * bank is organised by sound family (`fire-2`, `cure-2`, `ice`). Rather than
 * rewrite 210 records across folders other agents own, the data keeps its
 * authored keys and this one table translates them. `resolveSfx()` in
 * `./index.ts` applies it, and `AudioManager.playSfx` goes through that, so a
 * presenter can pass an ability's `sfxKey` straight through.
 *
 * `tests/unit/audio-sfx-aliases.test.ts` walks every ability, aeon and item in
 * both games' catalogues and fails if any `sfxKey` resolves to nothing — so the
 * day someone adds an ability, this table cannot rot silently into every spell
 * falling back to a generic hit.
 *
 * Mapping rules, so new entries stay consistent:
 * - Tiers stay tiered: Fire / Fira / Firaga -> `fire` / `fire-2` / `fire-3`.
 * - Lulu's Fury versions sound like the spell they repeat.
 * - Breaks and status-inflicting skills use their STATUS cue (`blind`,
 *   `silence`, `debuff-generic`): the presenter already plays the hit itself on
 *   the damage event, so the ability cue is the flourish, not the impact.
 * - An aeon Overdrive uses the effect it looks like (Hellfire -> `fire-3`),
 *   not the generic `aeon-overdrive` swell.
 * - Pure data: no imports, so `./index.ts` can import it without a cycle.
 */
export const SFX_ALIASES: Readonly<Record<string, string>> = {
  // ------------------------------------------------------------- black magic
  'sfx-fire-cast': 'fire',
  'sfx-fira-cast': 'fire-2',
  'sfx-firaga-cast': 'fire-3',
  'sfx-blizzard-cast': 'ice',
  'sfx-blizzara-cast': 'ice-2',
  'sfx-blizzaga-cast': 'ice-3',
  'sfx-thunder-cast': 'thunder',
  'sfx-thundara-cast': 'lightning-2',
  'sfx-thundaga-cast': 'lightning-3',
  'sfx-water-cast': 'water',
  'sfx-watera-cast': 'water-2',
  'sfx-waterga-cast': 'water-3',
  'sfx-bio-cast': 'bio',
  'sfx-death-cast': 'death',
  'sfx-demi-cast': 'gravity',
  'sfx-drain-cast': 'drain',
  'sfx-osmose-cast': 'osmose',
  'sfx-flare-cast': 'flare',
  'sfx-ultima-cast': 'ultima',

  // Lulu's Fury: each repeat sounds like the spell it repeats.
  'sfx-fire-fury-cast': 'fire',
  'sfx-fira-fury-cast': 'fire-2',
  'sfx-firaga-fury-cast': 'fire-3',
  'sfx-blizzard-fury-cast': 'ice',
  'sfx-blizzara-fury-cast': 'ice-2',
  'sfx-blizzaga-fury-cast': 'ice-3',
  'sfx-thunder-fury-cast': 'thunder',
  'sfx-thundara-fury-cast': 'lightning-2',
  'sfx-thundaga-fury-cast': 'lightning-3',
  'sfx-water-fury-cast': 'water',
  'sfx-watera-fury-cast': 'water-2',
  'sfx-waterga-fury-cast': 'water-3',
  'sfx-bio-fury-cast': 'bio',
  'sfx-death-fury-cast': 'death',
  'sfx-demi-fury-cast': 'gravity',
  'sfx-drain-fury-cast': 'drain',
  'sfx-osmose-fury-cast': 'osmose',
  'sfx-flare-fury-cast': 'flare',
  'sfx-ultima-fury-cast': 'ultima',

  // ------------------------------------------------------------- white magic
  'sfx-cure': 'cure',
  'sfx-cura': 'cure-2',
  'sfx-curaga': 'cure-3',
  'sfx-life': 'life',
  'sfx-full-life': 'full-life',
  'sfx-auto-life': 'life',
  'sfx-holy': 'holy',
  'sfx-esuna': 'esuna',
  'sfx-dispel': 'dispel',
  'sfx-haste': 'haste',
  'sfx-hastega': 'haste',
  'sfx-slow': 'slow',
  'sfx-slowga': 'slow',
  'sfx-protect': 'protect',
  'sfx-shell': 'shell',
  'sfx-reflect': 'reflect',
  'sfx-regen': 'regen',
  'sfx-nulblaze': 'buff-generic',
  'sfx-nulfrost': 'buff-generic',
  'sfx-nulshock': 'buff-generic',
  'sfx-nultide': 'buff-generic',

  // ---------------------------------------------------------------- skills
  'sfx-armor-break': 'debuff-generic',
  'sfx-magic-break': 'debuff-generic',
  'sfx-mental-break': 'debuff-generic',
  'sfx-power-break': 'debuff-generic',
  'sfx-full-break': 'debuff-generic',
  'sfx-dark-attack': 'blind',
  'sfx-dark-buster': 'blind',
  'sfx-silence-attack': 'silence',
  'sfx-silence-buster': 'silence',
  'sfx-sleep-attack': 'sleep',
  'sfx-sleep-buster': 'sleep',
  'sfx-zombie-attack': 'curse',
  'sfx-delay-attack': 'slow',
  'sfx-delay-buster': 'slow',
  'sfx-triple-foul': 'debuff-generic',
  'sfx-quick-hit': 'slash-light',
  'sfx-extract-ability': 'debuff-generic',
  'sfx-extract-mana': 'debuff-generic',
  'sfx-extract-power': 'debuff-generic',
  'sfx-extract-speed': 'debuff-generic',

  // --------------------------------------------------------------- specials
  'sfx-aim': 'buff-generic',
  'sfx-cheer': 'buff-generic',
  'sfx-focus': 'buff-generic',
  'sfx-luck': 'buff-generic',
  'sfx-reflex': 'buff-generic',
  'sfx-jinx': 'debuff-generic',
  'sfx-provoke': 'debuff-generic',
  'sfx-threaten': 'debuff-generic',
  'sfx-bribe': 'coin-tick',
  'sfx-spare-change': 'coin-tick',
  'sfx-pilfer-gil': 'steal-success',
  'sfx-nab-gil': 'steal-success',
  'sfx-mug': 'steal-success',
  'sfx-steal': 'steal-success',
  'sfx-copycat': 'magic-charge',
  'sfx-doublecast': 'magic-charge',
  'sfx-entrust': 'overdrive-full',
  'sfx-flee': 'escape',
  'sfx-guard': 'guard',
  'sfx-sentinel': 'guard',
  'sfx-lancet': 'drain',
  'sfx-pray': 'cure',
  'sfx-scan': 'scan',
  'sfx-talk': 'confirm',
  'sfx-use': 'item-use',
  'sfx-quick-pockets': 'item-use',

  // ------------------------------------------------------------- Overdrives
  'sfx-spiral-cut': 'slash-heavy',
  'sfx-slice-and-dice': 'dagger-flurry',
  'sfx-energy-rain': 'holy-2',
  'sfx-blitz-ace': 'ball-hit',
  'sfx-banishing-blade': 'slash-heavy',
  'sfx-dragon-fang': 'slash-heavy',
  'sfx-shooting-star': 'slash-heavy',
  'sfx-tornado': 'wind-gust',
  'sfx-grand-summon': 'summon',

  // Kimahri's Ronso Rage.
  'sfx-aqua-breath': 'water-3',
  'sfx-bad-breath': 'breath-attack',
  'sfx-fire-breath': 'breath-attack',
  'sfx-stone-breath': 'breath-attack',
  'sfx-doom': 'doom-tick',
  'sfx-kimahri-jump': 'slash-heavy',
  'sfx-mighty-guard': 'protect',
  'sfx-nova': 'ultima',
  'sfx-seed-cannon': 'gun-burst',
  'sfx-self-destruct': 'explosion',
  'sfx-thrust-kick': 'hit-2',
  'sfx-white-wind': 'cure-3',

  // Wakka's reels.
  'sfx-wakka-reels-spin': 'od-reel-spin',
  'sfx-wakka-shot-attack-reels': 'ball-hit',
  'sfx-wakka-shot-aurochs': 'ball-hit',
  'sfx-wakka-shot-break': 'ball-hit',
  'sfx-wakka-shot-havoc': 'ball-hit',
  'sfx-wakka-shot-power': 'ball-hit',
  'sfx-wakka-shot-fire': 'fire',
  'sfx-wakka-shot-ice': 'ice',
  'sfx-wakka-shot-thunder': 'thunder',
  'sfx-wakka-shot-water': 'water',
  'sfx-wakka-shot-time': 'stop',

  // ------------------------------------------------------------------ aeons
  'sfx-aeon-attack': 'slash-heavy',
  'sfx-aeon-boost': 'buff-generic',
  'sfx-aeon-shield': 'protect',
  'sfx-aeon-dismiss': 'summon-depart',
  'sfx-sonic-wings': 'slash-light',
  'sfx-aerospark': 'thunder',
  'sfx-meteor-strike': 'meteor',
  'sfx-heavenly-strike': 'ice-3',
  'sfx-impulse': 'explosion',
  'sfx-pain': 'death',
  'sfx-camisade': 'pierce',
  'sfx-passado': 'slash-light',
  'sfx-razzia': 'slash-heavy',
  'sfx-nul-all': 'buff-generic',
  'sfx-yojimbo-slash': 'sword-slash-2',
  'sfx-yojimbo-throw': 'pierce',

  // Aeon Overdrives: the effect each one looks like.
  'sfx-energy-ray': 'laser-fire',
  'sfx-energy-blast': 'explosion',
  'sfx-hellfire': 'fire-3',
  'sfx-diamond-dust': 'ice-3',
  'sfx-thors-hammer': 'lightning-3',
  'sfx-mega-flare': 'flare',
  'sfx-oblivion': 'ultima',
  'sfx-delta-attack': 'gravity-2',
  'sfx-zanmato': 'critical',

  // ------------------------------------------------------------------ items
  'sfx-item-heal-small': 'cure',
  'sfx-item-heal-medium': 'cure-2',
  'sfx-item-heal-party': 'cure-2',
  'sfx-item-heal-cure-party': 'cure-2',
  'sfx-item-heal-full': 'elixir',
  'sfx-item-heal-full-party': 'elixir',
  'sfx-item-heal-elemental': 'buff-generic',
  'sfx-item-mp-small': 'mp-restore',
  'sfx-item-mp-large': 'mp-restore',
  'sfx-item-revive': 'phoenix-down',
  'sfx-item-revive-party': 'phoenix-down',
  'sfx-item-cure': 'esuna',
  'sfx-item-cure-all': 'esuna',
  'sfx-item-salt-scatter': 'dispel',
  'sfx-item-buff': 'buff-generic',
  'sfx-item-buff-party': 'buff-generic',
  'sfx-item-haste': 'haste',
  'sfx-item-haste-party': 'haste',
  'sfx-item-distill': 'item-use',
  'sfx-item-hourglass': 'stop',
  'sfx-item-doom': 'doom-tick',
  'sfx-item-poison-bite': 'poison',
  'sfx-item-powder': 'sleep',
  'sfx-item-smoke': 'escape',
  'sfx-item-drain-hp': 'drain',
  'sfx-item-drain-mp': 'osmose',
  'sfx-item-drain-both': 'osmose',
  'sfx-item-death-shadow': 'death',
  'sfx-item-death-wind': 'death',
  'sfx-item-fire-small': 'fire',
  'sfx-item-fire-multi': 'fire-2',
  'sfx-item-fire-large': 'fire-3',
  'sfx-item-ice-small': 'ice',
  'sfx-item-ice-multi': 'ice-2',
  'sfx-item-ice-large': 'ice-3',
  'sfx-item-lightning-small': 'thunder',
  'sfx-item-lightning-multi': 'lightning-2',
  'sfx-item-lightning-large': 'lightning-3',
  'sfx-item-water-small': 'water',
  'sfx-item-water-multi': 'water-2',
  'sfx-item-water-large': 'water-3',
  'sfx-item-explosion-small': 'explosion',
  'sfx-item-explosion-large': 'explosion',
  'sfx-item-dark-matter-detonate': 'ultima',
  'sfx-item-shadow-burst': 'gravity-2',
  'sfx-item-gem-burst-holy': 'holy-2',
  'sfx-item-gem-burst-large': 'explosion',
  'sfx-item-gem-burst-massive': 'flare',
};
