/**
 * Core battle effects: swings, impacts, the fall, the fanfare.
 *
 * Rule 3 of the sound-effect rules governs this file — every impact has weight
 * below 90 Hz *and* a movement layer 30-50 ms before the transient. A hit with
 * no anticipation is a click, and clicks are what the old bank was made of.
 */

import {
  bell,
  bodyHit,
  breath,
  CHORDS,
  choirBloom,
  cloth,
  cymbalSwell,
  drone,
  glassHigh,
  LOW,
  lowStrings,
  MAGIC,
  scatter,
  stab,
  steelRing,
  subImpact,
  SUB,
  tamTam,
  timpani,
  UI,
  whoosh,
} from './materials.ts';
import type { SfxDesign } from './design.ts';

export const battleSfx: Record<string, SfxDesign> = {
  'sword-slash-1': {
    about: 'Tidus: cloth, a fast blade passing left to right, and a bright steel ring behind it.',
    category: 'weapon',
    length: 0.7,
    layers: [
      cloth({ at: 0, dur: 0.08, gain: 0.2 }),
      whoosh({ at: 0.035, dur: 0.18, from: 900, to: 3400, pan: -0.55, panTo: 0.45, gain: 0.34 }),
      steelRing({ at: 0.12, freq: 1568, dur: 0.42, gain: 0.26, pan: 0.2 }),
      glassHigh(UI.move, { at: 0.12, dur: 0.06, vel: 0.35, gain: 0.18, pan: 0.25 }),
    ],
  },

  'sword-slash-2': {
    about: 'A heavier two-handed cut right to left: more cloth, a lower blade, a longer ring.',
    category: 'weapon',
    length: 0.9,
    layers: [
      cloth({ at: 0, dur: 0.11, gain: 0.26 }),
      whoosh({ at: 0.04, dur: 0.24, from: 520, to: 2200, pan: 0.55, panTo: -0.45, gain: 0.4 }),
      steelRing({ at: 0.16, freq: 1174, dur: 0.6, gain: 0.3, pan: -0.2 }),
      subImpact({ at: 0.16, freq: SUB.move, dur: 0.22, gain: 0.3 }),
    ],
  },

  'hit-1': {
    about: 'A solid landed blow: cloth ahead of it, a drum body, sub weight on B1, a short steel edge.',
    category: 'impact',
    length: 0.9,
    layers: [
      cloth({ at: 0, dur: 0.06, gain: 0.18 }),
      bodyHit({ at: 0.04, vel: 0.8, gain: 0.6 }),
      subImpact({ at: 0.04, freq: SUB.home, dur: 0.4, gain: 0.5 }),
      steelRing({ at: 0.042, freq: 1174, dur: 0.3, gain: 0.16, pan: 0.15 }),
    ],
  },

  'hit-2': {
    about: 'A glancing blow: the same gesture lighter, shorter and higher, with less floor under it.',
    category: 'impact',
    length: 0.6,
    layers: [
      cloth({ at: 0, dur: 0.05, gain: 0.13 }),
      bodyHit({ at: 0.03, pitch: 'D2', vel: 0.62, gain: 0.45, speed: 1.15 }),
      subImpact({ at: 0.03, freq: SUB.home * 1.2, dur: 0.22, gain: 0.32 }),
      steelRing({ at: 0.032, freq: 1568, dur: 0.22, gain: 0.14, pan: -0.15 }),
    ],
  },

  critical: {
    about: 'Critical: the impact, an orchestral stab on the tonic triad, and a tam-tam opening behind it.',
    category: 'flourish',
    length: 2.4,
    layers: [
      cloth({ at: 0, dur: 0.06, gain: 0.2 }),
      bodyHit({ at: 0.04, vel: 0.9, gain: 0.6 }),
      subImpact({ at: 0.04, freq: SUB.home, dur: 0.5, gain: 0.55 }),
      ...stab(CHORDS.tonicLow, { at: 0.045, vel: 0.9, dur: 0.35, gain: 0.85 }),
      tamTam({ at: 0.05, dur: 1.4, vel: 0.7, gain: 0.3 }),
      steelRing({ at: 0.05, freq: 1568, dur: 0.7, gain: 0.2, pan: 0.25 }),
    ],
  },

  'ko-fall': {
    about: 'A fighter goes down: the cello falls a whole tone, the body lands, the tam-tam mourns it.',
    category: 'impact',
    length: 2.6,
    layers: [
      {
        kind: 'note',
        instrument: 'cello-solo',
        pitch: LOW.neutral,
        dur: 0.42,
        vel: 0.6,
        attack: 0.03,
        at: 0,
        gain: 0.42,
        pan: -0.2,
      },
      {
        kind: 'note',
        instrument: 'cello-solo',
        pitch: LOW.home,
        dur: 0.7,
        vel: 0.5,
        attack: 0.05,
        fade: 0.3,
        at: 0.26,
        gain: 0.38,
        pan: -0.2,
      },
      cloth({ at: 0.3, dur: 0.14, gain: 0.2 }),
      bodyHit({ at: 0.42, pitch: 'B1', vel: 0.75, gain: 0.5, speed: 0.92 }),
      subImpact({ at: 0.42, freq: SUB.deep * 1.3, dur: 0.6, gain: 0.45 }),
      tamTam({ at: 0.44, dur: 1.6, vel: 0.5, gain: 0.26 }),
    ],
  },

  footstep: {
    about: 'One boot on stone: a small body thud under a scrape of grit, nothing above 9 kHz.',
    category: 'impact',
    length: 0.34,
    top: 9000,
    layers: [
      bodyHit({ at: 0, pitch: 'D2', vel: 0.45, gain: 0.32, speed: 1.3 }),
      subImpact({ at: 0, freq: 78, dur: 0.14, gain: 0.22, curve: 5 }),
      {
        kind: 'air',
        at: 0.004,
        dur: 0.07,
        freq: 1600,
        freqTo: 700,
        q: 1.4,
        attack: 0.003,
        curve: 6,
        gain: 0.12,
        highpass: 500,
      },
    ],
  },

  'victory-fanfare': {
    about: 'The victory sting: one long horn note that falls rather than rises, answered by a plagal chord — relief, not a trophy.',
    category: 'flourish',
    length: 3.4,
    layers: [
      timpani('B2', { at: 0, dur: 0.4, vel: 0.7, gain: 0.34 }),
      {
        kind: 'note',
        instrument: 'horn',
        pitch: ['B3', 'F#4'],
        dur: 0.9,
        vel: 0.8,
        attack: 0.05,
        at: 0.02,
        gain: 0.42,
        pan: -0.25,
      },
      {
        kind: 'note',
        instrument: 'horn',
        pitch: ['A3', 'E4'],
        dur: 0.45,
        vel: 0.7,
        attack: 0.04,
        at: 0.95,
        gain: 0.38,
        pan: -0.25,
      },
      {
        kind: 'note',
        instrument: 'strings',
        pitch: CHORDS.amen,
        dur: 1.3,
        vel: 0.6,
        attack: 0.12,
        fade: 0.5,
        at: 1.4,
        gain: 0.36,
        pan: 0.15,
      },
      {
        kind: 'note',
        instrument: 'harp',
        pitch: ['B3', 'D4', 'F#4', 'B4'],
        roll: 0.055,
        dur: 0.8,
        vel: 0.55,
        at: 1.42,
        gain: 0.34,
        pan: -0.35,
      },
      cymbalSwell({ at: 1.3, dur: 1.2, vel: 0.4, gain: 0.16 }),
    ],
  },

  'boss-roar': {
    about: 'Something vast objects: low choir and basses under a rising snarl, with the floor moving.',
    category: 'flourish',
    length: 2.6,
    top: 8500,
    layers: [
      choirBloom(['B1', 'C#2'], { at: 0, dur: 1.4, vel: 0.7, gain: 0.4, voice: 'choir', attack: 0.06 }),
      lowStrings(['B1', 'F#2'], { at: 0, dur: 1.5, vel: 0.7, gain: 0.4, tremolo: true }),
      {
        kind: 'air',
        at: 0.02,
        dur: 1.1,
        freq: 180,
        freqTo: 520,
        q: 1.6,
        attack: 0.12,
        curve: 1.6,
        gain: 0.26,
      },
      subImpact({ at: 0, freq: SUB.deep, dur: 1.3, gain: 0.5, curve: 1.6 }),
      tamTam({ at: 0.6, dur: 1.6, vel: 0.6, gain: 0.24, speed: 0.8 }),
    ],
  },

  'machina-whir': {
    about: 'Machina spinning up: a hollow drone climbing under metal ticks, then steam let go.',
    category: 'ambience',
    length: 2.2,
    layers: [
      drone(['B2', 'F#3'], { at: 0, dur: 1.2, vel: 0.5, gain: 0.26, voice: 'pwm-lead' }),
      {
        kind: 'tone',
        at: 0.05,
        dur: 1.1,
        freq: 180,
        toFreq: 430,
        wave: 'tri',
        attack: 0.12,
        curve: 1.2,
        gain: 0.16,
        lowpass: 4000,
        pan: -0.2,
      },
      ...scatter(7, { at: 0.1, span: 0.9, freq: 2600, freqSpread: 0.5, dur: 0.035, gain: 0.1, seed: 4411 }),
      {
        kind: 'air',
        at: 1.15,
        dur: 0.8,
        freq: 3400,
        freqTo: 1200,
        q: 0.7,
        attack: 0.02,
        curve: 2.2,
        gain: 0.16,
        highpass: 800,
        pan: 0.3,
      },
      bell(MAGIC.neutral, { at: 1.2, dur: 0.4, vel: 0.3, gain: 0.14, pan: 0.25 }),
      breath({ at: 1.2, dur: 0.6, gain: 0.05 }),
    ],
  },
};
