/**
 * What the other side does: breath weapons, machina, the moment a boss changes
 * shape, and the small sad sound of an enemy dissolving into light.
 *
 * The boss material is the one place the score's dread register is allowed into
 * the effects — low strings on the b6, a tam-tam opening, the floor moving —
 * because those cues fire while that music is already playing and they have to
 * belong to it.
 */

import {
  bell,
  bodyHit,
  breath,
  choirBloom,
  cymbalSwell,
  drone,
  glassHigh,
  LOW,
  lowStrings,
  MAGIC,
  scatter,
  subImpact,
  SUB,
  suction,
  tamTam,
  timpani,
  toll,
  UI,
} from './materials.ts';
import type { SfxDesign } from './design.ts';

export const enemySfx: Record<string, SfxDesign> = {
  'breath-attack': {
    about: 'An elemental breath: a long roar of air over low choir, with the room shaking under it.',
    category: 'spell',
    length: 2.4,
    top: 9000,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 1.5,
        freq: 260,
        freqTo: 1400,
        q: 0.45,
        attack: 0.08,
        curve: 1.6,
        hold: 0.2,
        gain: 0.45,
      },
      choirBloom(['B1', 'D2', 'F#2'], { at: 0, dur: 1.4, vel: 0.65, gain: 0.34, voice: 'choir', attack: 0.06 }),
      subImpact({ at: 0, freq: SUB.deep, dur: 1.4, gain: 0.5, curve: 1.5 }),
      ...scatter(12, { at: 0.1, span: 1.1, freq: 1800, freqSpread: 1, dur: 0.05, gain: 0.08, seed: 3131 }),
      tamTam({ at: 0.8, dur: 1.4, vel: 0.6, gain: 0.22, speed: 0.85 }),
    ],
  },

  'laser-charge': {
    about: 'Vegnagun taking aim: a hollow tone climbing a minor third while air is pulled toward it.',
    category: 'spell',
    length: 1.6,
    layers: [
      {
        kind: 'tone',
        at: 0,
        dur: 1.2,
        freq: 247,
        toFreq: 587,
        wave: 'tri',
        attack: 0.15,
        curve: 1.1,
        gain: 0.26,
        lowpass: 3600,
      },
      suction({ at: 0.1, dur: 1, low: 500, high: 4000, gain: 0.2 }),
      drone(['B1', 'C#2'], { at: 0, dur: 1.2, vel: 0.5, gain: 0.24, voice: 'pwm-lead' }),
      glassHigh(UI.ache, { at: 1.05, dur: 0.08, vel: 0.4, gain: 0.2, pan: 0.2 }),
    ],
  },

  'laser-fire': {
    about: 'The beam: a held column of filtered air with a hard front edge and a hollow core.',
    category: 'spell',
    length: 1.8,
    top: 10_000,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 0.08,
        freq: 3600,
        freqTo: 1200,
        q: 0.7,
        attack: 0.001,
        curve: 8,
        gain: 0.5,
        seed: 606,
      },
      {
        kind: 'air',
        at: 0.02,
        dur: 1.2,
        freq: 1400,
        q: 1.4,
        attack: 0.02,
        curve: 1.2,
        hold: 0.55,
        gain: 0.3,
      },
      {
        kind: 'tone',
        at: 0.02,
        dur: 1.1,
        freq: 587,
        toFreq: 493,
        wave: 'tri',
        attack: 0.01,
        curve: 1.3,
        hold: 0.5,
        gain: 0.2,
        lowpass: 4200,
      },
      subImpact({ at: 0.01, freq: SUB.move, dur: 1.1, gain: 0.4, curve: 1.4 }),
    ],
  },

  explosion: {
    about: 'A real explosion: the crack, the weight, and debris still settling a second later.',
    category: 'impact',
    length: 2.4,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 0.12,
        freq: 2600,
        freqTo: 500,
        q: 0.45,
        attack: 0.001,
        curve: 7,
        gain: 0.5,
        seed: 4242,
      },
      bodyHit({ at: 0, pitch: 'B1', vel: 0.95, gain: 0.6, speed: 0.85 }),
      subImpact({ at: 0, freq: SUB.deep, dur: 1.1, gain: 0.6, curve: 2.2 }),
      {
        kind: 'air',
        at: 0.04,
        dur: 1.3,
        freq: 420,
        freqTo: 110,
        q: 0.4,
        attack: 0.02,
        curve: 2,
        gain: 0.3,
        seed: 99,
      },
      ...scatter(14, { at: 0.35, span: 1.2, freq: 1600, freqSpread: 1, dur: 0.04, gain: 0.07, seed: 515 }),
      tamTam({ at: 0.02, dur: 1.6, vel: 0.7, gain: 0.24 }),
    ],
  },

  quake: {
    about: 'The ground fails: a long low rumble with the timpani rolling and rock falling through it.',
    category: 'impact',
    length: 3.2,
    top: 8000,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 2.6,
        freq: 150,
        freqTo: 70,
        q: 0.5,
        attack: 0.25,
        curve: 1.3,
        gain: 0.38,
        seed: 808,
      },
      subImpact({ at: 0, freq: SUB.deep, dur: 2.4, gain: 0.55, curve: 1.2 }),
      timpani('B1', { at: 0.1, dur: 1.6, vel: 0.7, gain: 0.3 }),
      timpani('D2', { at: 0.9, dur: 1.4, vel: 0.6, gain: 0.24, pan: -0.15 }),
      ...scatter(10, { at: 0.5, span: 1.8, freq: 900, freqSpread: 1.1, dur: 0.06, gain: 0.08, seed: 1717 }),
      lowStrings(['B1', 'C#2'], { at: 0.2, dur: 1.8, vel: 0.5, gain: 0.24, tremolo: true }),
    ],
  },

  whip: {
    about: 'A tentacle lash: air narrowing to a point, a crack, and wet weight behind it.',
    category: 'weapon',
    length: 0.9,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 0.2,
        freq: 600,
        freqTo: 3400,
        q: 1.8,
        attack: 0.03,
        curve: 3,
        gain: 0.34,
        pan: -0.4,
        panTo: 0.4,
      },
      {
        kind: 'air',
        at: 0.19,
        dur: 0.05,
        freq: 3000,
        freqTo: 1000,
        q: 0.9,
        attack: 0.001,
        curve: 8,
        gain: 0.42,
        pan: 0.35,
        seed: 313,
      },
      bodyHit({ at: 0.2, pitch: 'D2', vel: 0.7, gain: 0.36, speed: 1.1 }),
      subImpact({ at: 0.2, freq: 88, dur: 0.3, gain: 0.3, curve: 4 }),
    ],
  },

  'dissolve-pyreflies': {
    about: 'An enemy comes apart into light: the body lets go, and what is left rises and is beautiful.',
    category: 'ambience',
    length: 3,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 0.5,
        freq: 700,
        freqTo: 2000,
        q: 0.8,
        attack: 0.05,
        curve: 2,
        gain: 0.16,
      },
      choirBloom([MAGIC.tense, MAGIC.home], { at: 0.1, dur: 1.4, vel: 0.45, gain: 0.28, attack: 0.2 }),
      ...[MAGIC.move, UI.home, UI.neutral, UI.move, UI.high, MAGIC.high].map((pitch, i) => glassHigh(pitch, {
        at: 0.25 + i * 0.22,
        dur: 0.14,
        vel: 0.4 - i * 0.03,
        gain: 0.3 - i * 0.025,
        pan: i % 2 === 0 ? -0.35 : 0.36,
      })),
      breath({ at: 0.2, dur: 1.8, gain: 0.06 }),
      bell(UI.home, { at: 1.1, dur: 1, vel: 0.3, gain: 0.16, pan: 0.15 }),
    ],
  },

  'machina-destroy': {
    about: 'Machina killed: metal tears, sparks scatter, and the drone it was running on dies away.',
    category: 'impact',
    length: 2.4,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 0.1,
        freq: 2200,
        freqTo: 600,
        q: 0.5,
        attack: 0.001,
        curve: 7,
        gain: 0.45,
        seed: 2468,
      },
      bodyHit({ at: 0, pitch: 'B1', vel: 0.85, gain: 0.5, speed: 0.9 }),
      subImpact({ at: 0, freq: SUB.deep * 1.2, dur: 0.9, gain: 0.5, curve: 2.4 }),
      { kind: 'ring', at: 0.02, freq: 620, ratio: 3.73, index: 2.2, indexTo: 0.1, dur: 0.9, curve: 3, gain: 0.22, pan: -0.2 },
      ...scatter(16, { at: 0.12, span: 1.3, freq: 2800, freqSpread: 1, dur: 0.03, gain: 0.07, seed: 1234 }),
      drone(['B1', 'C#2'], { at: 0.05, dur: 1.2, vel: 0.5, gain: 0.2, voice: 'pwm-lead' }),
      cymbalSwell({ at: 0.05, dur: 1.2, vel: 0.5, gain: 0.16 }),
    ],
  },

  'boss-phase-shift': {
    about: 'A boss becomes something else: strings rise on the b6, the tam-tam opens, and it lands.',
    category: 'flourish',
    length: 3.4,
    layers: [
      lowStrings([LOW.tense, 'B2'], { at: 0, dur: 1.6, vel: 0.6, gain: 0.34, tremolo: true }),
      choirBloom(['G2', 'B2'], { at: 0.2, dur: 1.5, vel: 0.5, gain: 0.26, voice: 'choir', attack: 0.3 }),
      cymbalSwell({ at: 0.4, dur: 1.5, vel: 0.6, gain: 0.2 }),
      suction({ at: 0.6, dur: 1.2, low: 400, high: 3000, gain: 0.16 }),
      subImpact({ at: 1.8, freq: SUB.deep, dur: 1.1, gain: 0.6, curve: 2 }),
      timpani('B1', { at: 1.8, dur: 0.9, vel: 0.9, gain: 0.4 }),
      tamTam({ at: 1.8, dur: 1.5, vel: 0.8, gain: 0.3 }),
      toll(LOW.home, { at: 1.82, dur: 1.4, vel: 0.6, gain: 0.3 }),
    ],
  },

  'boss-overdrive-warning': {
    about: 'Something terrible is being charged: a tremolo climb under an accelerating bell, no resolution.',
    category: 'spell',
    length: 2.6,
    layers: [
      lowStrings(['B1', 'C#2'], { at: 0, dur: 2, vel: 0.55, gain: 0.3, tremolo: true }),
      ...[0, 0.5, 0.9, 1.2, 1.44, 1.62, 1.75, 1.85].map((at, i) => bell(i % 2 === 0 ? MAGIC.ache : MAGIC.tense, {
        at,
        dur: 0.3,
        vel: 0.4 + i * 0.045,
        gain: 0.26 + i * 0.02,
        pan: i % 2 === 0 ? -0.2 : 0.22,
      })),
      suction({ at: 0.9, dur: 1.1, low: 500, high: 3600, gain: 0.18 }),
      subImpact({ at: 1.9, freq: SUB.home, dur: 0.6, gain: 0.34, curve: 2.4 }),
    ],
  },

  'petrify-shatter': {
    about: 'Stone closing over, then breaking: a granular crackle that tightens, and glass giving way.',
    category: 'impact',
    length: 2,
    layers: [
      ...scatter(18, { at: 0, span: 0.85, freq: 1400, freqSpread: 0.9, dur: 0.035, gain: 0.09, seed: 7373 }),
      drone(['B2', 'C#3'], { at: 0, dur: 0.9, vel: 0.45, gain: 0.2 }),
      {
        kind: 'air',
        at: 0.9,
        dur: 0.12,
        freq: 3200,
        freqTo: 1200,
        q: 0.6,
        attack: 0.001,
        curve: 7,
        gain: 0.4,
        seed: 919,
      },
      ...[UI.tense, UI.move, MAGIC.high, UI.neutral].map((pitch, i) => glassHigh(pitch, {
        at: 0.9 + i * 0.03,
        dur: 0.1,
        vel: 0.5,
        gain: 0.26,
        pan: i % 2 === 0 ? -0.35 : 0.35,
      })),
      subImpact({ at: 0.9, freq: SUB.home, dur: 0.5, gain: 0.4, curve: 3 }),
      ...scatter(10, { at: 1, span: 0.6, freq: 2600, freqSpread: 1, dur: 0.03, gain: 0.06, seed: 606 }),
    ],
  },
};
