/**
 * The upper tiers, and the spells that have no base version.
 *
 * A tier is not the same sound louder. Going up a tier adds a *second gesture*:
 * Fira is two waves of flame where Fire is one, Firaga puts a sub-bass whoomp
 * in front of both and a choir behind them. The pitch material never changes —
 * everything stays inside B minor — so a Firaga and a cursor tick still belong
 * to the same game.
 */

import {
  bell,
  breath,
  CHORDS,
  choirBloom,
  cymbalSwell,
  drone,
  glassHigh,
  LOW,
  lowStrings,
  MAGIC,
  scatter,
  shimmer,
  sopranoLine,
  subImpact,
  SUB,
  suction,
  tamTam,
  timpani,
  toll,
  UI,
  pizz,
} from './materials.ts';
import type { DesignLayer, SfxDesign } from './design.ts';

/** One wave of flame: air roaring through a band, with crackle riding it. */
function flameWave(at: number, dur: number, gain: number, pan: number, seed: number): DesignLayer[] {
  return [
    {
      kind: 'air',
      at,
      dur,
      freq: 300,
      freqTo: 1200,
      q: 0.5,
      attack: 0.035,
      curve: 2.2,
      hold: 0.12,
      gain,
      pan,
      seed,
    },
    ...scatter(8, { at: at + 0.05, span: dur * 0.7, freq: 2400, freqSpread: 0.9, dur: 0.04, gain: 0.08, seed: seed + 11 }),
  ];
}

/** A crack of lightning: the strike, a metallic arc, and the room answering. */
function strike(at: number, gain: number, pan: number, seed: number): DesignLayer[] {
  return [
    {
      kind: 'air',
      at,
      dur: 0.08,
      freq: 4200,
      freqTo: 900,
      q: 0.5,
      attack: 0.0012,
      curve: 8,
      gain,
      pan,
      seed,
    },
    {
      kind: 'ring',
      at: at + 0.004,
      freq: 988,
      ratio: 3.41,
      index: 2.2,
      indexTo: 0.15,
      dur: 0.26,
      curve: 5,
      gain: gain * 0.4,
      pan: -pan,
    },
  ];
}

export const spellSfx: Record<string, SfxDesign> = {
  'fire-2': {
    about: 'Fira: two waves of flame overlapping, the second wider, with the choir low underneath.',
    category: 'spell',
    length: 2.2,
    top: 9500,
    layers: [
      ...flameWave(0, 0.8, 0.4, -0.2, 9101),
      ...flameWave(0.45, 0.9, 0.34, 0.25, 4243),
      subImpact({ at: 0, freq: 84, dur: 0.6, gain: 0.42 }),
      choirBloom(['B2', 'D3'], { at: 0.05, dur: 1.1, vel: 0.55, gain: 0.26, voice: 'choir', attack: 0.06 }),
      tamTam({ at: 0.05, dur: 1.2, vel: 0.5, gain: 0.16 }),
    ],
  },

  'fire-3': {
    about: 'Firaga: a sub-bass whoomp opens the ground, two firestorm waves roll through, the choir sears above.',
    category: 'spell',
    length: 3.4,
    top: 9500,
    layers: [
      subImpact({ at: 0, freq: SUB.deep, dur: 1.2, gain: 0.6, curve: 1.8 }),
      timpani('B1', { at: 0, dur: 0.8, vel: 0.85, gain: 0.3 }),
      ...flameWave(0.08, 1, 0.42, -0.25, 9101),
      ...flameWave(0.75, 1.2, 0.4, 0.28, 4243),
      choirBloom(['B2', 'D3', 'F#3'], { at: 0.1, dur: 1.8, vel: 0.65, gain: 0.3, voice: 'choir', attack: 0.08 }),
      sopranoLine(MAGIC.tense, { at: 0.9, dur: 1.2, vel: 0.5, gain: 0.22, pan: 0.2 }),
      tamTam({ at: 0.1, dur: 2, vel: 0.75, gain: 0.24 }),
      ...scatter(10, { at: 1.6, span: 1.2, freq: 1600, freqSpread: 1, dur: 0.05, gain: 0.06, seed: 6161 }),
    ],
  },

  'ice-2': {
    about: 'Blizzara: a denser hail of glass with a longer freeze behind it and real cold underneath.',
    category: 'spell',
    length: 2.3,
    layers: [
      ...[UI.high, UI.move, MAGIC.high, UI.neutral, MAGIC.move, UI.tense, MAGIC.ache].map((pitch, i) => glassHigh(pitch, {
        at: 0.02 + i * 0.05,
        dur: 0.12,
        vel: 0.55 - i * 0.04,
        gain: 0.3,
        pan: i % 2 === 0 ? -0.35 : 0.35,
      })),
      {
        kind: 'air',
        at: 0,
        dur: 0.8,
        freq: 6600,
        freqTo: 2200,
        q: 1,
        attack: 0.015,
        curve: 2.4,
        gain: 0.2,
        highpass: 1200,
      },
      choirBloom([MAGIC.move, MAGIC.high], { at: 0.15, dur: 1.3, vel: 0.45, gain: 0.26 }),
      subImpact({ at: 0.1, freq: 62, dur: 0.5, gain: 0.32 }),
      ...shimmer({ at: 0.5, dur: 1, spread: 0.6, gain: 0.16 }),
    ],
  },

  'ice-3': {
    about: 'Blizzaga: a glacier arrives — shard hail, a deep frozen impact, and a wide shimmer over the wreckage.',
    category: 'spell',
    length: 3.2,
    layers: [
      ...[UI.high, UI.move, MAGIC.high, UI.neutral, MAGIC.move, UI.tense, MAGIC.ache, UI.home].map((pitch, i) => glassHigh(pitch, {
        at: 0.02 + i * 0.045,
        dur: 0.14,
        vel: 0.6 - i * 0.035,
        gain: 0.32,
        pan: i % 2 === 0 ? -0.4 : 0.4,
      })),
      {
        kind: 'air',
        at: 0,
        dur: 1,
        freq: 7200,
        freqTo: 1800,
        q: 0.9,
        attack: 0.02,
        curve: 2.2,
        gain: 0.22,
        highpass: 1000,
      },
      subImpact({ at: 0.42, freq: SUB.deep * 1.15, dur: 1, gain: 0.55, curve: 2.2 }),
      timpani('D2', { at: 0.42, dur: 0.7, vel: 0.8, gain: 0.28 }),
      choirBloom([MAGIC.move, MAGIC.high, 'D6'], { at: 0.45, dur: 1.6, vel: 0.55, gain: 0.3, attack: 0.1 }),
      toll(MAGIC.home, { at: 0.44, dur: 1.4, vel: 0.5, gain: 0.26 }),
      ...shimmer({ at: 1, dur: 1.4, spread: 0.8, gain: 0.18 }),
    ],
  },

  lightning: {
    about: 'A bolt: one hard crack, a short arc, and a rumble that leaves the room ringing.',
    category: 'spell',
    length: 1.8,
    layers: [
      ...strike(0, 0.5, 0.1, 1212),
      {
        kind: 'air',
        at: 0.03,
        dur: 1.2,
        freq: 260,
        freqTo: 90,
        q: 0.45,
        attack: 0.03,
        curve: 2,
        gain: 0.28,
        pan: -0.1,
        seed: 777,
      },
      subImpact({ at: 0.02, freq: SUB.home, dur: 0.8, gain: 0.45, curve: 2.4 }),
    ],
  },

  'lightning-2': {
    about: 'Thundara: two cracks half a beat apart, a longer arc, and heavier weather behind them.',
    category: 'spell',
    length: 2.4,
    layers: [
      ...strike(0, 0.46, -0.2, 1212),
      ...strike(0.22, 0.42, 0.25, 3434),
      {
        kind: 'air',
        at: 0.05,
        dur: 1.6,
        freq: 300,
        freqTo: 85,
        q: 0.45,
        attack: 0.04,
        curve: 1.8,
        gain: 0.3,
        seed: 777,
      },
      subImpact({ at: 0.02, freq: SUB.home, dur: 1.2, gain: 0.5, curve: 2 }),
      timpani('B1', { at: 0.22, dur: 0.8, vel: 0.8, gain: 0.28 }),
    ],
  },

  'lightning-3': {
    about: 'Thundaga: three strikes, a roaring arc, and a storm rolling out across the whole hall.',
    category: 'spell',
    length: 3.2,
    layers: [
      ...strike(0, 0.45, -0.3, 1212),
      ...strike(0.18, 0.42, 0.3, 3434),
      ...strike(0.42, 0.48, 0, 5656),
      {
        kind: 'air',
        at: 0.05,
        dur: 2.2,
        freq: 320,
        freqTo: 80,
        q: 0.42,
        attack: 0.05,
        curve: 1.6,
        gain: 0.32,
        seed: 777,
      },
      subImpact({ at: 0.42, freq: SUB.deep, dur: 1.6, gain: 0.58, curve: 1.8 }),
      timpani('B1', { at: 0.42, dur: 1.1, vel: 0.9, gain: 0.32 }),
      tamTam({ at: 0.44, dur: 1.8, vel: 0.7, gain: 0.22 }),
      choirBloom(['B2', 'C#3'], { at: 0.5, dur: 1.5, vel: 0.5, gain: 0.2, voice: 'choir', attack: 0.12 }),
    ],
  },

  'water-2': {
    about: 'Watera: two surges, the second breaking over the first, with spray between them.',
    category: 'spell',
    length: 2.4,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 1,
        freq: 640,
        freqTo: 2200,
        q: 0.55,
        attack: 0.12,
        curve: 1.6,
        hold: 0.15,
        gain: 0.34,
        pan: -0.2,
      },
      {
        kind: 'air',
        at: 0.6,
        dur: 1.1,
        freq: 1900,
        freqTo: 380,
        q: 0.6,
        attack: 0.05,
        curve: 2,
        gain: 0.3,
        pan: 0.25,
        seed: 3366,
      },
      ...scatter(12, { at: 0.3, span: 1.1, freq: 3000, freqSpread: 0.8, dur: 0.05, gain: 0.08, seed: 5150 }),
      choirBloom([MAGIC.home, MAGIC.move], { at: 0.1, dur: 1.4, vel: 0.45, gain: 0.24 }),
      subImpact({ at: 0.55, freq: 70, dur: 0.6, gain: 0.34 }),
    ],
  },

  'water-3': {
    about: 'Waterga: the tide comes in — a deep surge, twin swells, wide spray, and a crash that empties the room.',
    category: 'spell',
    length: 3.4,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 1.3,
        freq: 420,
        freqTo: 1800,
        q: 0.5,
        attack: 0.25,
        curve: 1.4,
        hold: 0.2,
        gain: 0.36,
        pan: -0.25,
      },
      {
        kind: 'air',
        at: 0.9,
        dur: 1.4,
        freq: 2200,
        freqTo: 320,
        q: 0.55,
        attack: 0.06,
        curve: 1.8,
        gain: 0.34,
        pan: 0.3,
        seed: 3366,
      },
      ...scatter(16, { at: 0.5, span: 1.6, freq: 3200, freqSpread: 0.9, dur: 0.05, gain: 0.07, seed: 5150 }),
      subImpact({ at: 0.85, freq: SUB.deep * 1.1, dur: 1.2, gain: 0.5, curve: 2 }),
      choirBloom([MAGIC.home, MAGIC.move, MAGIC.high], { at: 0.2, dur: 1.9, vel: 0.5, gain: 0.26, attack: 0.18 }),
      cymbalSwell({ at: 0.6, dur: 1.4, vel: 0.5, gain: 0.16 }),
      tamTam({ at: 0.9, dur: 1.6, vel: 0.55, gain: 0.18 }),
    ],
  },

  'holy-2': {
    about: 'Grand Holy: a peal of tubular bells inside a wide choir chord, with the soprano over the top.',
    category: 'flourish',
    length: 3.6,
    layers: [
      toll(MAGIC.home, { at: 0, dur: 1.6, vel: 0.75, gain: 0.45 }),
      toll(MAGIC.move, { at: 0.18, dur: 1.5, vel: 0.6, gain: 0.32, pan: -0.25 }),
      toll(UI.home, { at: 0.36, dur: 1.4, vel: 0.55, gain: 0.28, pan: 0.28 }),
      choirBloom(CHORDS.open, { at: 0.05, dur: 2.2, vel: 0.65, gain: 0.4, attack: 0.15 }),
      sopranoLine(UI.home, { at: 0.5, dur: 1.6, vel: 0.55, gain: 0.3, pan: -0.1 }),
      ...shimmer({ at: 0.4, dur: 1.8, spread: 0.9, gain: 0.2 }),
      cymbalSwell({ at: 0.1, dur: 1.8, vel: 0.45, gain: 0.14 }),
      timpani('B1', { at: 0, dur: 0.9, vel: 0.7, gain: 0.26 }),
    ],
  },

  gravity: {
    about: 'Demi: space folding inward — a descending hollow tone and air dragged after it.',
    category: 'spell',
    length: 2,
    top: 8500,
    layers: [
      {
        kind: 'tone',
        at: 0,
        dur: 1.1,
        freq: 330,
        toFreq: 62,
        wave: 'sine',
        attack: 0.04,
        curve: 1.6,
        gain: 0.34,
        lowpass: 2400,
      },
      suction({ at: 0, dur: 0.9, low: 300, high: 2200, gain: 0.2 }),
      drone(['B1', 'C#2'], { at: 0.1, dur: 1.1, vel: 0.5, gain: 0.24 }),
      subImpact({ at: 0.85, freq: SUB.deep, dur: 0.8, gain: 0.45, curve: 2.6 }),
    ],
  },

  'gravity-2': {
    about: 'Demi at full weight: the same collapse, slower, ending on an impact that flattens the floor.',
    category: 'spell',
    length: 2.8,
    top: 8500,
    layers: [
      {
        kind: 'tone',
        at: 0,
        dur: 1.5,
        freq: 392,
        toFreq: 46,
        wave: 'sine',
        attack: 0.05,
        curve: 1.4,
        gain: 0.36,
        lowpass: 2200,
      },
      suction({ at: 0, dur: 1.3, low: 260, high: 2600, gain: 0.22 }),
      lowStrings(['B1', 'C#2'], { at: 0.2, dur: 1.3, vel: 0.55, gain: 0.26, tremolo: true }),
      subImpact({ at: 1.3, freq: SUB.deep, dur: 1.2, gain: 0.6, curve: 2.2 }),
      timpani('B1', { at: 1.3, dur: 0.9, vel: 0.9, gain: 0.34 }),
      tamTam({ at: 1.32, dur: 1.4, vel: 0.6, gain: 0.2 }),
    ],
  },

  flare: {
    about: 'Flare: everything collapses toward one point, holds for an instant, and detonates white-hot.',
    category: 'spell',
    length: 3.2,
    layers: [
      suction({ at: 0, dur: 1.1, low: 400, high: 5000, gain: 0.26 }),
      {
        kind: 'tone',
        at: 0.1,
        dur: 1,
        freq: 247,
        toFreq: 988,
        wave: 'tri',
        attack: 0.2,
        curve: 1.1,
        gain: 0.2,
        lowpass: 5000,
      },
      // The instant of silence before it goes off is the loudest part of the cue.
      {
        kind: 'air',
        at: 1.2,
        dur: 0.14,
        freq: 3200,
        freqTo: 600,
        q: 0.45,
        attack: 0.001,
        curve: 7,
        gain: 0.5,
        seed: 1919,
      },
      subImpact({ at: 1.2, freq: SUB.deep, dur: 1.3, gain: 0.6, curve: 2 }),
      ...stabChord(1.2),
      choirBloom(CHORDS.tonic, { at: 1.25, dur: 1.5, vel: 0.6, gain: 0.3, attack: 0.06 }),
      ...shimmer({ at: 1.5, dur: 1.3, spread: 0.8, gain: 0.18 }),
    ],
  },

  ultima: {
    about: 'Ultima: a long gathering, a detonation that takes the room with it, and light still falling afterwards.',
    category: 'flourish',
    length: 3.8,
    layers: [
      suction({ at: 0, dur: 1.4, low: 300, high: 4600, gain: 0.24 }),
      choirBloom(['B2', 'F#3'], { at: 0, dur: 1.4, vel: 0.5, gain: 0.24, voice: 'choir', attack: 0.4 }),
      lowStrings(['B1', 'C#2'], { at: 0.3, dur: 1.2, vel: 0.6, gain: 0.26, tremolo: true }),
      {
        kind: 'air',
        at: 1.5,
        dur: 0.16,
        freq: 2800,
        freqTo: 500,
        q: 0.4,
        attack: 0.001,
        curve: 6,
        gain: 0.5,
        seed: 2929,
      },
      subImpact({ at: 1.5, freq: SUB.deep, dur: 1.6, gain: 0.62, curve: 1.6 }),
      timpani('B1', { at: 1.5, dur: 1.2, vel: 0.95, gain: 0.34 }),
      tamTam({ at: 1.52, dur: 2, vel: 0.85, gain: 0.3 }),
      toll(MAGIC.home, { at: 1.55, dur: 1.8, vel: 0.65, gain: 0.3 }),
      choirBloom(CHORDS.open, { at: 1.6, dur: 1.9, vel: 0.65, gain: 0.34, attack: 0.1 }),
      ...shimmer({ at: 2.2, dur: 1.4, spread: 1, gain: 0.16 }),
    ],
  },

  bio: {
    about: 'Bio: something viscous, bubbling low in the field, with a sickly held note inside it.',
    category: 'spell',
    length: 2.2,
    top: 7000,
    layers: [
      ...scatter(20, { at: 0, span: 1.5, freq: 520, freqSpread: 1.2, dur: 0.07, gain: 0.1, seed: 4747 }),
      {
        kind: 'tone',
        at: 0,
        dur: 1.4,
        freq: 138,
        toFreq: 116,
        wave: 'tri',
        attack: 0.15,
        curve: 1.4,
        gain: 0.24,
        vibrato: 0.035,
        vibratoRate: 4.5,
        lowpass: 1400,
      },
      drone(['C#2', 'G2'], { at: 0.1, dur: 1.3, vel: 0.45, gain: 0.22 }),
      {
        kind: 'air',
        at: 0.1,
        dur: 1.2,
        freq: 380,
        freqTo: 900,
        q: 0.8,
        attack: 0.1,
        curve: 1.8,
        gain: 0.16,
      },
    ],
  },

  death: {
    about: 'Death: a cold choir breath falling away, one bell tolled underneath, and nothing else.',
    category: 'spell',
    length: 3,
    layers: [
      choirBloom(['G2', 'B2', 'C#3'], { at: 0, dur: 1.4, vel: 0.5, gain: 0.32, voice: 'choir', attack: 0.25 }),
      toll(LOW.home, { at: 0.35, dur: 1.6, vel: 0.6, gain: 0.36 }),
      breath({ at: 0, dur: 1.2, gain: 0.07, reverse: true }),
      tamTam({ at: 0.4, dur: 1.8, vel: 0.5, gain: 0.2, speed: 0.9 }),
      subImpact({ at: 0.35, freq: SUB.deep, dur: 1.2, gain: 0.3, curve: 1.6 }),
    ],
  },

  'doom-tick': {
    about: 'Doom: one small bell on the 2, struck as if by a clock, with the hall too quiet around it.',
    category: 'ui',
    length: 0.9,
    peak: 0.55,
    layers: [
      bell(MAGIC.ache, { dur: 0.4, vel: 0.5, gain: 0.5 }),
      pizz(LOW.ache, { at: 0.002, vel: 0.4, gain: 0.2, pan: 0.15 }),
    ],
  },

  drain: {
    about: 'Drain: air and choir pulled backwards out of the target and into the caster.',
    category: 'spell',
    length: 2,
    layers: [
      suction({ at: 0, dur: 1, low: 340, high: 2600, gain: 0.26, pan: 0.3 }),
      {
        kind: 'note',
        instrument: 'choir',
        pitch: ['B2', 'D3'],
        dur: 0.9,
        vel: 0.5,
        reverse: true,
        attack: 0.05,
        at: 0.1,
        gain: 0.3,
        pan: 0.2,
      },
      bell(MAGIC.home, { at: 1, dur: 0.6, vel: 0.45, gain: 0.3, pan: -0.25 }),
      subImpact({ at: 0.98, freq: 72, dur: 0.4, gain: 0.26 }),
    ],
  },

  osmose: {
    about: 'Osmose: the same siphon an octave up and made of glass — thin, cold and quick.',
    category: 'spell',
    length: 1.6,
    layers: [
      suction({ at: 0, dur: 0.8, low: 1200, high: 5200, gain: 0.22, pan: 0.3 }),
      {
        kind: 'note',
        instrument: 'glockenspiel',
        pitch: [MAGIC.move, UI.home],
        dur: 0.5,
        vel: 0.45,
        reverse: true,
        at: 0.2,
        gain: 0.26,
        pan: 0.2,
      },
      glassHigh(UI.high, { at: 0.8, dur: 0.1, vel: 0.5, gain: 0.34, pan: -0.25 }),
      ...shimmer({ at: 0.82, dur: 0.6, spread: 0.3, gain: 0.16 }),
    ],
  },

  meteor: {
    about: 'Meteor: three whistles falling out of the sky at different distances, and three impacts under them.',
    category: 'flourish',
    length: 3.6,
    layers: [
      ...[0, 0.35, 0.7].flatMap((at, i): DesignLayer[] => [
        {
          kind: 'air',
          at,
          dur: 0.9,
          freq: 3200 - i * 400,
          freqTo: 420,
          q: 2.6,
          attack: 0.08,
          curve: 1.6,
          gain: 0.2,
          pan: i === 0 ? -0.4 : i === 1 ? 0.4 : 0,
          seed: 1000 + i,
        },
        {
          kind: 'air',
          at: at + 0.9,
          dur: 0.12,
          freq: 2200,
          freqTo: 400,
          q: 0.45,
          attack: 0.001,
          curve: 7,
          gain: 0.42,
          pan: i === 0 ? -0.35 : i === 1 ? 0.35 : 0,
          seed: 2000 + i,
        },
        subImpact({ at: at + 0.9, freq: SUB.deep * (1 + i * 0.1), dur: 0.9, gain: 0.5, curve: 2.2 }),
        timpani(i === 0 ? 'B1' : i === 1 ? 'D2' : 'F#1', { at: at + 0.9, dur: 0.7, vel: 0.85, gain: 0.26 }),
      ]),
      tamTam({ at: 1.6, dur: 1.8, vel: 0.7, gain: 0.22 }),
      ...scatter(12, { at: 1.8, span: 1.4, freq: 1400, freqSpread: 1, dur: 0.05, gain: 0.06, seed: 8181 }),
    ],
  },
};

/** The brass-and-strings hit inside Flare's detonation. Declared after use for readability. */
function stabChord(at: number): DesignLayer[] {
  return [
    {
      kind: 'note',
      instrument: 'brass-stab',
      pitch: CHORDS.tonicLow,
      dur: 0.35,
      vel: 0.9,
      attack: 0.012,
      at,
      gain: 0.4,
      pan: -0.15,
    },
    {
      kind: 'note',
      instrument: 'strings-short',
      pitch: CHORDS.tonic,
      dur: 0.3,
      vel: 0.85,
      attack: 0.01,
      at,
      gain: 0.3,
      pan: 0.2,
    },
    { kind: 'note', instrument: 'timpani', pitch: 'B1', dur: 0.7, vel: 0.9, at, gain: 0.3, pan: 0.1 },
  ];
}
