/**
 * Cues the story fires between battles: weather on Gagazet, the fayth humming,
 * the Farplane, a whistle answered across a valley.
 *
 * These are the longest and quietest things in the bank, and three of them are
 * not sound design at all but music heard from somewhere else in the building —
 * the fayth and Lenne's phrase take their notes straight from
 * `tracks/themes.ts`, because a leitmotif heard faintly is still the leitmotif.
 */

import { HYMN_HEAD, SONGSTRESS_HOOK } from '../tracks/themes.ts';
import {
  breath,
  choirBloom,
  drone,
  LOW,
  MAGIC,
  motif,
  scatter,
  shimmer,
  sopranoLine,
  subImpact,
  SUB,
  tamTam,
  toll,
} from './materials.ts';
import type { SfxDesign } from './design.ts';

export const storySfx: Record<string, SfxDesign> = {
  'wind-high-altitude': {
    about: 'Summit wind: a cold low bed with one thin keening line drifting slowly across it.',
    category: 'ambience',
    length: 3.6,
    top: 9000,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 3.4,
        freq: 420,
        freqTo: 260,
        q: 0.5,
        attack: 0.4,
        curve: 1.1,
        hold: 0.4,
        gain: 0.3,
        seed: 1001,
      },
      {
        kind: 'air',
        at: 0.3,
        dur: 2.8,
        freq: 2400,
        freqTo: 3400,
        q: 6,
        attack: 0.6,
        curve: 1.1,
        hold: 0.3,
        gain: 0.13,
        pan: -0.5,
        panTo: 0.5,
        seed: 2002,
      },
      drone([LOW.home, LOW.move], { at: 0.2, dur: 2.6, vel: 0.35, gain: 0.14 }),
      breath({ at: 0.5, dur: 2.4, gain: 0.04 }),
    ],
  },

  'wind-gust': {
    about: 'One gust: it arrives, whistles past from left to right, and takes the top of the field with it.',
    category: 'ambience',
    length: 2.4,
    layers: [
      {
        kind: 'air',
        at: 0,
        dur: 1.8,
        freq: 600,
        freqTo: 1800,
        q: 0.6,
        attack: 0.35,
        curve: 1.5,
        hold: 0.15,
        gain: 0.34,
        pan: -0.6,
        panTo: 0.6,
        seed: 3003,
      },
      {
        kind: 'air',
        at: 0.35,
        dur: 1.1,
        freq: 2800,
        q: 5,
        attack: 0.25,
        curve: 1.6,
        gain: 0.12,
        pan: -0.3,
        panTo: 0.45,
        seed: 4004,
      },
      ...scatter(5, { at: 0.4, span: 0.9, freq: 1200, freqSpread: 0.9, dur: 0.08, gain: 0.05, seed: 5005 }),
    ],
  },

  'kimahri-roar': {
    about: 'A Ronso cries out in grief, not threat: a torn falling line over breath, and it breaks at the end.',
    category: 'flourish',
    length: 2.8,
    top: 8000,
    layers: [
      {
        kind: 'note',
        instrument: 'cello-solo',
        pitch: 'F#2',
        dur: 0.8,
        vel: 0.85,
        attack: 0.04,
        at: 0,
        gain: 0.42,
        pan: -0.15,
      },
      {
        kind: 'note',
        instrument: 'cello-solo',
        pitch: 'D2',
        dur: 1,
        vel: 0.6,
        attack: 0.06,
        fade: 0.4,
        at: 0.75,
        gain: 0.36,
        pan: -0.15,
      },
      choirBloom(['B1', 'F#2'], { at: 0, dur: 1.5, vel: 0.7, gain: 0.3, voice: 'choir', attack: 0.05 }),
      {
        kind: 'air',
        at: 0.02,
        dur: 1.4,
        freq: 320,
        freqTo: 900,
        q: 1.1,
        attack: 0.1,
        curve: 1.7,
        gain: 0.22,
      },
      subImpact({ at: 0, freq: SUB.deep, dur: 1.2, gain: 0.34, curve: 1.6 }),
      tamTam({ at: 0.7, dur: 1.6, vel: 0.5, gain: 0.2, speed: 0.85 }),
    ],
  },

  'fayth-hum': {
    about: 'The fayth: the hymn\'s four-note head sung wordlessly, harmonised underneath, hanging in the air.',
    category: 'ambience',
    length: 3.8,
    layers: [
      ...motif(HYMN_HEAD, { instrument: 'choir-ooh', root: 64, bpm: 52, at: 0.15, gain: 0.34, vel: 0.5, attack: 0.18, legato: 1.1 }),
      choirBloom(['E2', 'B2'], { at: 0, dur: 2.6, vel: 0.45, gain: 0.24, voice: 'choir', attack: 0.5 }),
      sopranoLine('E5', { at: 1.6, dur: 1.4, vel: 0.4, gain: 0.2, pan: -0.15 }),
      ...shimmer({ at: 1.2, dur: 1.6, spread: 1.1, gain: 0.12 }),
      breath({ at: 0.4, dur: 2, gain: 0.04 }),
    ],
  },

  'dome-echo': {
    about: 'One sound in a stone hall: a struck bell answered three times, each answer darker and further away.',
    category: 'ambience',
    length: 3.6,
    layers: [
      toll(LOW.home, { at: 0, dur: 1.2, vel: 0.6, gain: 0.4 }),
      toll(LOW.home, { at: 0.62, dur: 1, vel: 0.4, gain: 0.22, pan: -0.35 }),
      toll(LOW.home, { at: 1.3, dur: 0.9, vel: 0.28, gain: 0.14, pan: 0.38 }),
      toll(LOW.home, { at: 2.05, dur: 0.8, vel: 0.2, gain: 0.08, pan: -0.2 }),
      drone([LOW.home, LOW.move], { at: 0, dur: 2.6, vel: 0.35, gain: 0.14 }),
    ],
    top: 6500,
  },

  'yu-yevon-chant': {
    about: 'A chant with something wrong inside it: two choirs a half-step apart over a drone that never resolves.',
    category: 'ambience',
    length: 3.8,
    top: 7000,
    layers: [
      choirBloom(['B2', 'F#3'], { at: 0, dur: 2.6, vel: 0.5, gain: 0.3, voice: 'choir', attack: 0.5 }),
      choirBloom(['C3', 'G3'], { at: 0.5, dur: 2.2, vel: 0.4, gain: 0.2, voice: 'choir', attack: 0.6 }),
      drone(['B1'], { at: 0, dur: 3.2, vel: 0.5, gain: 0.24 }),
      subImpact({ at: 0, freq: SUB.deep, dur: 3, gain: 0.26, curve: 1.1 }),
      tamTam({ at: 1.4, dur: 1.8, vel: 0.45, gain: 0.16, speed: 0.8 }),
    ],
  },

  'machina-groan': {
    about: 'Old machina under load: inharmonic metal bending slowly, with the structure creaking around it.',
    category: 'ambience',
    length: 3.2,
    top: 7000,
    layers: [
      { kind: 'ring', at: 0, freq: 116, ratio: 2.41, index: 2.4, indexTo: 0.8, dur: 2.4, curve: 1.3, gain: 0.3, pan: -0.2 },
      { kind: 'ring', at: 0.4, freq: 87, ratio: 3.17, index: 2, indexTo: 0.5, dur: 2, curve: 1.2, gain: 0.22, pan: 0.25 },
      drone(['B1', 'C#2'], { at: 0, dur: 2.6, vel: 0.5, gain: 0.22, voice: 'pwm-lead' }),
      ...scatter(8, { at: 0.5, span: 2, freq: 1400, freqSpread: 1.1, dur: 0.06, gain: 0.06, seed: 6006 }),
      subImpact({ at: 0, freq: SUB.deep, dur: 2.4, gain: 0.3, curve: 1.1 }),
    ],
  },

  'farplane-voices': {
    about: 'Voices rising out of the Farplane: four entries at four distances, none of them together.',
    category: 'ambience',
    length: 3.8,
    layers: [
      choirBloom(['B3', 'F#4'], { at: 0, dur: 1.8, vel: 0.4, gain: 0.22, attack: 0.5, pan: -0.4 }),
      choirBloom(['D4', 'B4'], { at: 0.6, dur: 1.8, vel: 0.35, gain: 0.18, attack: 0.55, pan: 0.42 }),
      choirBloom(['F#4', 'C#5'], { at: 1.3, dur: 1.6, vel: 0.3, gain: 0.15, attack: 0.6, pan: -0.2 }),
      sopranoLine(MAGIC.high, { at: 1.9, dur: 1.4, vel: 0.38, gain: 0.18, pan: 0.2 }),
      ...shimmer({ at: 1, dur: 2, spread: 1.4, gain: 0.1 }),
      breath({ at: 0, dur: 2.6, gain: 0.04 }),
    ],
  },

  'lenne-song': {
    about: "Lenne's phrase carried from somewhere else: the songstress hook, one voice, no accompaniment but air.",
    category: 'ambience',
    length: 3.6,
    layers: [
      ...motif(SONGSTRESS_HOOK, { instrument: 'soprano', root: 68, bpm: 76, at: 0.2, gain: 0.34, vel: 0.5, attack: 0.12, legato: 1.15 }),
      ...motif(SONGSTRESS_HOOK, { instrument: 'choir-ooh', root: 56, bpm: 76, at: 0.24, gain: 0.16, vel: 0.4, attack: 0.25, legato: 1.2, pan: -0.3 }),
      drone(['G#2', 'D#3'], { at: 0, dur: 2.8, vel: 0.35, gain: 0.14 }),
      breath({ at: 0.1, dur: 2.2, gain: 0.04 }),
      ...shimmer({ at: 1.6, dur: 1.4, spread: 1, gain: 0.1 }),
    ],
  },

  'whistle-answer': {
    about: 'A two-finger whistle, and after a long pause a fainter one answering from across the valley.',
    category: 'ambience',
    length: 3.4,
    layers: [
      {
        kind: 'tone',
        at: 0,
        dur: 0.4,
        freq: 1480,
        toFreq: 1976,
        wave: 'sine',
        attack: 0.03,
        curve: 2.4,
        gain: 0.34,
        vibrato: 0.012,
        vibratoRate: 5.5,
        pan: -0.15,
      },
      {
        kind: 'air',
        at: 0,
        dur: 0.4,
        freq: 2600,
        q: 7,
        attack: 0.03,
        curve: 2.4,
        gain: 0.08,
        pan: -0.15,
      },
      // The pause is the cue. Nothing fills it.
      {
        kind: 'tone',
        at: 1.7,
        dur: 0.45,
        freq: 1480,
        toFreq: 1760,
        wave: 'sine',
        attack: 0.06,
        curve: 2,
        gain: 0.12,
        vibrato: 0.01,
        vibratoRate: 5,
        pan: 0.45,
        lowpass: 3200,
      },
      {
        kind: 'air',
        at: 1.2,
        dur: 1.6,
        freq: 500,
        freqTo: 900,
        q: 0.6,
        attack: 0.4,
        curve: 1.4,
        gain: 0.07,
        pan: 0.3,
        seed: 7007,
      },
    ],
  },
};
