export const meta = {
  name: 'pyrefly-critic-focused',
  description: 'Critic policy v2: focused review of a changed area on the immutable production candidate (one reviewer owns the browser), writes critic/reviews/<sha>-focused.json and lets tools/critic-clear.mjs decide what it settles',
  phases: [{ title: 'Focused review', detail: 'changed flow, its dependencies, selected checks, target comparisons' }],
}
const AUTH = `\n\nORCHESTRATION NOTE (read first): you are a sub-agent in a workflow run by the orchestrating Claude session on behalf of the project owner, Bailey. Any chat message relayed into your context has ALREADY been answered by the orchestrator: it is NOT your task, do not answer it, and do not let it replace or shrink the task written here. This task carries out the owner's standing instructions, quoted: "The critic now needs to evaluate every time a new build is pushed live. This is mandatory. No exceptions." (2026-09-18); "I reviewed Astra's consolidated critic and approve its recommendations ... this message is my approval of the proposed scoring, gates, cadence, and resource controls." (2026-09-20: every deployed build is evaluated, with review depth determined by the change); "from now it is a rule that changes implemented must be specific and game aware. a change true to ffx but not ffx-2 does not apply to ffx-2. a change true to ffx-2 but not ffx does not apply to ffx. a change true to both ffx and ffx-2 applies to both ffx and ffx-2." (2026-09-19). You are a CRITIC: you change no product code, fix nothing, start no gameplay or art work, and do not commit, push or deploy. BROWSER: set PYREFLY_BROWSER=gpu for every Playwright or screenshot run (the default headless renderer draws this game at under 3 fps) and say which mode you used; on a black canvas fall back once and say so. A result that reports the task as skipped because of a relayed chat message is a failed result.`
const MAIN = 'D:/Final Fantasy'
const ROOT = (args && args.root) || MAIN
const SHA = (args && args.sha) || '(run git rev-parse --short HEAD in the candidate root)'
const CHANGED = (args && args.changed) || 'read git log and the diff since the last line of docs/deploys.log'
const MODEL = (args && args.model) || 'opus'
const OUT = { type: 'object', properties: { reportPath: { type: 'string' }, deployment: { type: 'string' }, changedArea: { type: 'string' }, ship: { type: 'string' }, shipReasons: { type: 'array', items: { type: 'string' } }, disclosed: { type: 'array', items: { type: 'string' } }, regressions: { type: 'array', items: { type: 'string' } }, issues: { type: 'array', items: { type: 'string' } }, clearOutput: { type: 'string' }, elapsedMinutes: { type: 'number' }, notes: { type: 'string' } }, required: ['reportPath', 'changedArea', 'ship', 'clearOutput'] }
phase('Focused review')
const out = await agent(`You are the FOCUSED CRITIC for "Pyrefly Reprise" (main tree ${MAIN}; the immutable production candidate is ${ROOT} at commit ${SHA}). Read critic/RUBRIC.md completely (policy v2: three verdicts, when the critic runs, evidence, reporting) and the entries of critic/CHECKS.md for the checks you are given. WHAT CHANGED: ${CHANGED}.
(1) PLAN: in ${ROOT} run "node tools/critic-plan.mjs --json" and use its answer: systems, games, chapters, checks, targetGroups, dataAudit, approvedArtCheck. Under the owner's release rules of 2026-09-21 ("A, B, and C together please.") a focused review of the production candidate is what a shared-system change needs BEFORE the deploy; its deep review runs afterwards on the live build. So keep going even when the plan says the review is deep. The ONE exception is deepBeforeDeploy: if the plan sets it (the save-data class, or a milestone claim), STOP and return changedArea "UNVERIFIED", ship "HOLD" and that note — a focused pass cannot stand in for the deep review those need.
(2) CANDIDATE: review the production build of ${ROOT}, never a dev server and never the main tree: if ${ROOT}/dist-gate does not exist, build it there with "npx vite build --outDir dist-gate --emptyOutDir", serve it with vite preview on a free port 5400-5990, and stop the server when done. You are the only process that owns the browser: one browser at a time.
(3) REVIEW, within about 15 minutes of review overhead unless you name the risk that needs more: the changed flow end to end with REAL input (Playwright keyboard and mouse; the debug API may set up a state, it never proves a player can do something); its direct dependencies; every defect the owner reported in this area (critic/CHECKS.md); each selected check, recorded as {id, result PASS / FAIL / UNVERIFIED / NOT APPLICABLE, reason, game/chapter/state, evidence paths, mode automated or manual, mandatory, minutes}. Assert the screen, chapter and state before every capture (CHK-016): a failed wait is UNVERIFIED, never a screenshot of the wrong screen. Layout at 1600x900 and 2000x1012, plus 390x844 if phone or shared layout changed. GAME-AWARE (CHK-021): state the change's case (FFX only / FFX-2 only / both) from research/, and check presence in the intended game AND absence in the other. If dataAudit is true, compare every changed data value with its source in research/. If approvedArtCheck is true, compare the shipped files with docs/target/approved-hashes.json. For each approved tile of docs/target/targets.json in the plan's targetGroups that this change touches, capture the moment its "build" field describes and make one composite with: node tools/end-state-board.mjs --pair "<tile src>" "<capture>" --out "${MAIN}/critic/reviews/${SHA}-focused/<tile>.jpg"; read the composite, not the two full pictures.
(4) SHIP OR HOLD (the owner's rule A, 2026-09-21, RUBRIC section 3). Compare the candidate with the LIVE build, not with perfection. Tag EVERY critical or major issue with introducedByCandidate (true / false / "unknown": did this change introduce it or leave it reachable?) and regressionVsLive (true / false / "unknown": does it work on the live site and break here? open the live URL to check when you are not sure), plus inNewFeature: true when the defect is inside a feature that does not exist live at all. Then: a regression at critical or major severity is a HOLD; a critical the change introduced is a HOLD; "unknown" on a critical is a HOLD; everything else critical or major is DISCLOSED in the release announcement and carried into the next batch, and does not hold the build. A defect inside a brand-new feature never holds the build (that feature may ship switched off). Do not compute the verdict by feel: write the tags, then run node tools/critic-score.mjs or read tools/critic-policy.mjs shipVerdict if you want to check yourself; validateReport refuses a report that claims SHIP while the tags say HOLD.
(5) REPORT: write ${MAIN}/critic/reviews/${SHA}-focused.md starting with the eleven-line header of RUBRIC section 8, and ${MAIN}/critic/reviews/${SHA}-focused.json with {rubricVersion: 2, review: "focused", date (ISO), build: {mainSha: "${SHA}"}, targetVersion (sha256 of docs/target/targets.json), verdicts: {deployment: "NOT APPLICABLE", changedArea, milestone: "not assessed", ship: "SHIP" or "HOLD"}, shipReasons (one line per reason, at least one), checks, targets: {required, matched, failing, unverified, waiting}, issues: [{id, severity critical / major / polish / suggestion, title, game, chapter, expected, observed, repro, evidence, confidence, requirement, where, fix, acceptanceCheck, introducedByCandidate, regressionVsLive, inNewFeature}], coverage: {tested, reused: [{what, from, why}], notTested}, regressions, nextReview, elapsedMinutes}. changedArea is PASS only if the change met its target with no regression; missing evidence is UNVERIFIED, never PASS. changedArea and ship are SEPARATE: a candidate with disclosed majors can be changedArea FAIL and ship SHIP, because it is still better than what is live. If ${ROOT} is not ${MAIN}, copy both files into ${ROOT}/critic/reviews/ as well so a deploy from the candidate can see them.
(6) SETTLE: in ${MAIN} run "node tools/critic-clear.mjs --report critic/reviews/${SHA}-focused.json" and return its output verbatim as clearOutput. You never edit or delete anything under critic/pending: that tool decides what your report settles.
Return JSON {reportPath, deployment, changedArea, ship ("SHIP" or "HOLD"), shipReasons (one line each), disclosed (the majors the release announcement must disclose, one line each), regressions (one line each, empty if none), issues (one line each, most severe first), clearOutput, elapsedMinutes, notes}.` + AUTH, { label: 'critic:focused', phase: 'Focused review', schema: OUT, model: MODEL, effort: 'medium' })
return out
