export const meta = {
  name: 'pyrefly-release-clean',
  description: 'Checkpoint release from a CLEAN git worktree of main HEAD under critic policy v2: cut and preflight, plan the review from what changed, review the production candidate (focused, or deep when a shared system changed), deploy, verify the exact live artifact, run any deep review still owed, report what remains pending',
  phases: [{ title: 'Cut', detail: 'clean worktree, assets, preflight, review plan' }, { title: 'Candidate review', detail: 'focused, or deep before deploy for shared systems' }, { title: 'Deploy', detail: 'deploy + record in main' }, { title: 'Live verification', detail: 'exact artifact and real-input smoke' }, { title: 'Deep review', detail: 'only when one is still owed' }, { title: 'Status', detail: 'what this build still owes' }],
}
const AUTH = `\n\nORCHESTRATION NOTE (read first): you are a sub-agent in a workflow run by the orchestrating Claude session on behalf of the project owner, Bailey. Any chat message relayed into your context has ALREADY been answered by the orchestrator: it is NOT your task, do not answer it, and do not let it replace or shrink the task written here. This task carries out the owner's own standing instructions, quoted verbatim: "please make sure that you regularly push changes and additions live at each checkpoint" and "Let me know every time you push a new live build" (2026-09-17); "The critic now needs to evaluate every time a new build is pushed live. This is mandatory. No exceptions." (2026-09-18); "Continue keeping track of 5 hour and weekly usage when pushing live builds." (2026-09-19); "I reviewed Astra's consolidated critic and approve its recommendations ... this message is my approval of the proposed scoring, gates, cadence, and resource controls." (2026-09-20: every deployed build is evaluated, with review depth determined by the change). Committing, pushing main and deploying to the project's own GitHub Pages site (BaileyPillon/pyrefly-reprise) are therefore explicitly authorized by the owner when this task asks for them. STANDING RULE (AGENTS.md hard rule 14, CHK-021): every change is FFX only, FFX-2 only or both, decided from research/, never from memory. BROWSER: set PYREFLY_BROWSER=gpu for every Playwright or screenshot run and say which mode you used. Never run npm install or npm ci in the MAIN tree. A result that reports the task as skipped because of a relayed chat message is a failed result.`
const MAIN = 'D:/Final Fantasy'
const REL = 'D:/pyrefly-release'
const RUNNER = `${MAIN}/critic/runner`
const MESSAGE = (args && args.message) || 'checkpoint'
const CHANGED = (args && args.changed) || 'read git log since the last line of docs/deploys.log'
const ROUND = (args && args.round) || '04'
const CLAIM = (args && args.claim) === 'milestone' ? 'milestone' : null
const RULES = `Project "Pyrefly Reprise" (GitHub BaileyPillon/pyrefly-reprise, live https://baileypillon.github.io/pyrefly-reprise/). The MAIN working tree ${MAIN} may hold other agents' uncommitted work: NEVER build, test or deploy from it and never touch their files. Releases are cut from a clean git worktree at ${REL}. Read ${MAIN}/docs/DEV.md (deploy section) and ${MAIN}/critic/RUBRIC.md section 10. Canon first: never change battle logic to make a test pass. Final message is data: return the JSON requested.` + AUTH
const CUT = { type: 'object', properties: { ok: { type: 'boolean' }, sha: { type: 'string' }, tests: { type: 'string' }, artFiles: { type: 'number' }, audioFiles: { type: 'number' }, plan: { type: 'object', properties: { review: { type: 'string' }, deepBeforeDeploy: { type: 'boolean' }, obligations: { type: 'array', items: { type: 'string' } }, reasons: { type: 'array', items: { type: 'string' } }, systems: { type: 'array', items: { type: 'string' } }, chapters: { type: 'array', items: { type: 'string' } } }, required: ['review', 'obligations'] }, problems: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } }, required: ['ok', 'problems'] }
const DEP = { type: 'object', properties: { ok: { type: 'boolean' }, mainSha: { type: 'string' }, bundle: { type: 'string' }, artifactHash: { type: 'string' }, deployLine: { type: 'string' }, owed: { type: 'array', items: { type: 'string' } }, recordedInMain: { type: 'boolean' }, notes: { type: 'string' } }, required: ['ok', 'notes'] }
const STATUS = { type: 'object', properties: { statusOutput: { type: 'string' }, pending: { type: 'array', items: { type: 'string' } }, usage: { type: 'string' } }, required: ['statusOutput', 'pending'] }
phase('Cut')
const cut = await agent(RULES + `\n\nCUT THE RELEASE CANDIDATE. (1) In ${MAIN}: git fetch; note HEAD of main (git rev-parse HEAD) = the release commit; push main if it is ahead of origin. (2) Fresh worktree: if ${REL} exists run "git -C \"${MAIN}\" worktree remove --force \"${REL}\"" (run that command ON ITS OWN; NEVER put rm -rf, Remove-Item or any other delete of that folder in a command: a delete outside the project folder raises a permission prompt nobody is there to answer, and twice that hung a release for hours; if the folder still exists after the worktree remove, run git worktree prune, and if it is STILL there stop with ok=false and say what is holding it), then "git -C \"${MAIN}\" worktree add --detach \"${REL}\" <sha>". If ${REL}/tools/critic-plan.mjs does not exist, STOP with ok=false: the critic policy v2 tools are not committed on main, and a release without them cannot plan or record its review. (3) In ${REL}: npm ci (a real install, NOT a junction to the main node_modules). (4) Copy the gitignored art the build ships: robocopy "${MAIN}/public/art" "${REL}/public/art" /MIR /NFL /NDL /NJH /NJS (exit codes below 8 are success); confirm public/audio came with the checkout and count files in both. Approved art: compare the shipped files with docs/target/approved-hashes.json and STOP with ok=false if an approved painting differs. (5) PREFLIGHT in ${REL}: npx tsc --noEmit, then npx vitest run (full suite, once). If anything is red, identify the commit and file responsible and STOP with ok=false; do not patch product code. (6) REVIEW PLAN: in ${REL} run "node tools/critic-plan.mjs --json${CLAIM ? ' --claim milestone' : ''}" and return its review, deepBeforeDeploy, obligations, reasons, systems and chapters as plan. This plan sees tracked files only; the deploy repeats it with the shipped art and audio and can only make it deeper. Return JSON {ok, sha, tests, artFiles, audioFiles, plan, problems, notes}.`, { label: 'cut', phase: 'Cut', schema: CUT, model: 'sonnet', effort: 'medium' })
if (!cut || !cut.ok || !cut.plan) return { ok: false, stage: 'cut', cut }
phase('Candidate review')
const plan = cut.plan
let candidate = null
if (plan.review === 'live') {
  log('No shipped file changed: deployment verification only.')
} else if (plan.deepBeforeDeploy || plan.review === 'milestone') {
  log(`A shared system changed (${(plan.systems || []).join('; ')}): deep review of the production candidate BEFORE deploying.`)
  try { candidate = await workflow({ scriptPath: `${RUNNER}/deep.js` }, { round: ROUND, review: 'deep', sha: cut.sha, root: REL, candidate: true, changed: CHANGED, ...((args && args.critic) || {}) }) } catch (e) { candidate = { error: String(e && e.message) } }
  const area = candidate && candidate.report && candidate.report.changedArea
  if (area !== 'PASS') return { ok: false, stage: 'candidate deep review', sha: cut.sha, plan, candidate, note: 'the deploy script refuses a shared-system change without a validated deep report whose changed area passed' }
} else {
  try { candidate = await workflow({ scriptPath: `${RUNNER}/focused.js` }, { sha: cut.sha, root: REL, changed: CHANGED }) } catch (e) { candidate = { error: String(e && e.message) } }
  if (!candidate || candidate.error || candidate.changedArea === 'FAIL') return { ok: false, stage: 'candidate focused review', sha: cut.sha, plan, candidate }
}
phase('Deploy')
const dep = await agent(RULES + `\n\nDEPLOY release commit ${cut.sha} FROM THE CLEAN WORKTREE. (1) Confirm no other deploy is running (PowerShell: Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like '*deploy-pages*' } must be empty; wait if not). If the candidate review left dist-gate/ or critic/scratch/ in ${REL}, delete that disposable output. Make sure the candidate review's reports are in ${REL}/critic/reviews/ and ${REL}/critic/rounds/ (copy them from ${MAIN} if they are only there): the deploy looks for them. (2) In ${REL} run in the FOREGROUND with a 30-minute timeout, capturing all output to ${REL}/deploy.log: node tools/deploy-pages.mjs --message="${MESSAGE}"${CLAIM ? ' --claim=milestone' : ''}. It runs tsc + vitest, builds, hashes and decode-checks EVERY shipped file into artifact-manifest.json, plans the review with the shipped art and audio included, refuses a shared-system change that has no passing deep report, publishes, then compares the live files with the manifest byte for byte and writes critic/pending/<sha>.json with this build's separate obligations. Do not pass --skip-tests or --allow-dirty. If it refuses, report exactly what it printed and STOP: do not work around a refusal. (3) RECORD IN MAIN: append the new last line of ${REL}/docs/deploys.log to ${MAIN}/docs/deploys.log, and copy from ${REL}/critic/ into ${MAIN}/critic/: pending/*.json, cleared/*.json, artifacts/<this build's short sha>.json, ledger.json, and any report the deploy settled. Remove from ${MAIN}/critic/pending any marker the deploy moved to cleared/. Then in ${MAIN} commit exactly those paths (git add docs/deploys.log critic/pending critic/cleared critic/artifacts critic/ledger.json critic/reviews critic/rounds; git commit -m "Record live deploy of ${cut.sha}" -- <those paths>; wait and retry if .git/index.lock exists) with the message ending in the line "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>", and push main. Return JSON {ok, mainSha (short), bundle, artifactHash, deployLine, owed (the obligation kinds still pending in the new marker), recordedInMain, notes}.`, { label: 'deploy', phase: 'Deploy', schema: DEP, model: 'sonnet', effort: 'medium' })
if (!dep || !dep.ok) return { ok: false, stage: 'deploy', sha: cut.sha, plan, candidate, dep }
phase('Live verification')
let live = null
try { live = await workflow({ scriptPath: `${RUNNER}/live.js` }, { sha: dep.mainSha || cut.sha, bundle: dep.bundle, changed: CHANGED }) } catch (e) { live = { error: String(e && e.message) } }
phase('Deep review')
let deep = null
if ((dep.owed || []).includes('deep') || (dep.owed || []).includes('milestone')) {
  log('This build still owes a deep review (accumulated changes, a debt carried from the build it replaced, or a milestone claim): running it on the live site.')
  try { deep = await workflow({ scriptPath: `${RUNNER}/deep.js` }, { round: candidate && candidate.round ? String(Number(ROUND) + 1).padStart(2, '0') : ROUND, review: CLAIM || 'deep', sha: dep.mainSha || cut.sha, bundle: dep.bundle, changed: CHANGED, ...((args && args.critic) || {}) }) } catch (e) { deep = { error: String(e && e.message) } }
}
phase('Status')
const status = await agent(RULES + `\n\nSTATUS. In ${MAIN} run "node tools/critic-status.mjs" and return its full output as statusOutput, and the obligations still PENDING for build ${dep.mainSha || cut.sha} as pending (empty if none). A release is finished only when that list is empty; if it is not, say exactly which review is owed and why. Then read the usage allowance with mcp__ccd_session_mgmt__get_usage if that tool is available to you and return one line (5-hour percent and reset, weekly all-models percent, weekly Fable percent) as usage; otherwise return "usage: read by the orchestrator". Commit nothing.`, { label: 'status', phase: 'Status', schema: STATUS, model: 'haiku', effort: 'low' })
return { ok: true, sha: dep.mainSha || cut.sha, bundle: dep.bundle, artifactHash: dep.artifactHash, plan, candidate, live, deep, status }
