/**
 * Generated by `node tools/exp-install.mjs table` from the namespace's idle sidecars; do not edit by hand.
 * The experimental Leblanc chapter's figures, as the surfaces outside the stage need them (art namespace `exp-leblanc`, `src/data/art/artNamespace.ts`):
 * each idle's size, where its feet are, and which way the painting faces (`tools/exp-art-table.mjs`).
 */
export interface ExpFigureMetrics {
  readonly width: number;
  readonly height: number;
  /** The row of the soles, in the painting's own pixels. */
  readonly baselineY: number;
  /** The way the painting faces (the sidecar's `facing`); `auto` when it says nothing. */
  readonly facing: 'right' | 'left' | 'front' | 'auto';
}

export const EXP_FIGURE_METRICS: Readonly<Record<string, ExpFigureMetrics>> = {
  'exp-leblanc-ffx2-dr-goon': { width: 577, height: 1379, baselineY: 1363, facing: 'left' },
  'exp-leblanc-ffx2-fem-goon': { width: 449, height: 1386, baselineY: 1370, facing: 'left' },
  'exp-leblanc-leblanc': { width: 805, height: 1403, baselineY: 1387, facing: 'left' },
  'exp-leblanc-logos': { width: 825, height: 1400, baselineY: 1384, facing: 'left' },
  'exp-leblanc-ormi': { width: 819, height: 1379, baselineY: 1363, facing: 'left' },
  'exp-leblanc-paine-black-mage': { width: 567, height: 1151, baselineY: 1135, facing: 'auto' },
  'exp-leblanc-paine-gunner': { width: 493, height: 1136, baselineY: 1120, facing: 'auto' },
  'exp-leblanc-paine-songstress': { width: 344, height: 1194, baselineY: 1178, facing: 'left' },
  'exp-leblanc-paine-thief': { width: 735, height: 1181, baselineY: 1165, facing: 'right' },
  'exp-leblanc-paine-warrior': { width: 472, height: 1537, baselineY: 1521, facing: 'right' },
  'exp-leblanc-paine-white-mage': { width: 820, height: 1140, baselineY: 1124, facing: 'auto' },
  'exp-leblanc-rikku-alchemist': { width: 541, height: 1194, baselineY: 1178, facing: 'auto' },
  'exp-leblanc-rikku-black-mage': { width: 683, height: 1190, baselineY: 1174, facing: 'auto' },
  'exp-leblanc-rikku-gunner': { width: 364, height: 1062, baselineY: 1046, facing: 'auto' },
  'exp-leblanc-rikku-songstress': { width: 574, height: 1179, baselineY: 1163, facing: 'front' },
  'exp-leblanc-rikku-thief': { width: 773, height: 1523, baselineY: 1507, facing: 'right' },
  'exp-leblanc-rikku-warrior': { width: 648, height: 1214, baselineY: 1205, facing: 'right' },
  'exp-leblanc-rikku-white-mage': { width: 626, height: 1213, baselineY: 1197, facing: 'auto' },
  'exp-leblanc-yuna-black-mage': { width: 782, height: 1149, baselineY: 1133, facing: 'auto' },
  'exp-leblanc-yuna-gunner': { width: 674, height: 1548, baselineY: 1532, facing: 'right' },
  'exp-leblanc-yuna-songstress': { width: 655, height: 1116, baselineY: 1100, facing: 'auto' },
  'exp-leblanc-yuna-thief': { width: 767, height: 1176, baselineY: 1160, facing: 'right' },
  'exp-leblanc-yuna-warrior': { width: 728, height: 1183, baselineY: 1167, facing: 'auto' },
  'exp-leblanc-yuna-white-mage': { width: 581, height: 1183, baselineY: 1167, facing: 'right' },
};
