import type { PoseRegistrationTable } from './poseRegistrationTypes.ts';

/** Generated by `tools/posescale/measure.py table` from docs/target/pose-measure.json; do not edit by hand. */
export const POSE_REGISTRATION_FOES: PoseRegistrationTable = {
};
