/**
 * ElevenLabs music (2026-10-07): cues whose shipped file is a take generated by the ElevenLabs Music API, not a
 * render of our score.
 *
 * Bailey picked the takes by ear on 2026-10-07 (his words are in each cue's `pick`).
 * `docs/audio/music-elevenlabs-2026-10-07.json` is the record: what a person wrote down (the pick, the prompt, the raw
 * take's hash, both stereo variants) and what `tools/audio/music-elevenlabs.mjs measure` measured from the files in
 * `public/audio` (qa.mjs, quality-measure.py). This pins that the shipped files are the ones measured, that the
 * manifest entries that exempt themselves from the stale-render checks with a `source` are exactly the record's cues,
 * that each cue's old file is the one the earlier record pinned, that the gates were met or their failure is
 * disclosed, and that THEMES.md and CREDITS.md say what the record says. Everything is worked out from the record's
 * cue list, so a cue added to it or taken out of it needs no edit here.
 *
 * The older record tests (`audio-music-v2.test.ts`, `audio-music-o1.test.ts`) step aside for a cue this record lists.
 * Nothing here is a listening verdict (AGENTS.md rule 13). Game case: per cue, from the record (the Seymour battle
 * cues FFX only, the chapter select board and the title both games); the plumbing is both.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { hasTrack } from '../../src/audio/tracks/index.ts';
import { AUDIO_BUDGET_BYTES, externalSource } from '../../tools/audio/manifest-io.mjs';

const text = (p: string) => readFileSync(new URL(`../../${p}`, import.meta.url), 'utf8');
const read = (p: string) => JSON.parse(text(p));

interface Stereo {
  corr: number;
  sideMid: number;
  monoLoss: number;
}
interface EntryFields {
  loopStart: number;
  loopEnd: number;
  duration: number;
  bytes: number;
  lufs: number;
  truePeakDb: number;
}
interface Variant {
  dir: string;
  sha256: string;
  bytes: number;
  manifestEntry: EntryFields;
  stereo: Stereo;
}
interface Cue {
  cue: string;
  game: 'FFX' | 'FFX-2' | 'both';
  brief: string;
  /** The request body as sent: a text `prompt`, or a `composition_plan` (sections with their styles). */
  request: { prompt?: string; composition_plan?: { chunks: unknown[] } };
  raw: { sha256: string; bytes: number };
  before: { bytes: number; sha256: string; manifestEntry: EntryFields & { file: string } };
  variants: Record<string, Variant>;
  installedVariant: string | null;
  after: {
    bytes: number;
    sha256: string;
    decodedSamples: number;
    qa: { lufs: number; truePeakDb: number; seamOk: boolean; failures: string[] };
    measure: Stereo & { cliff: { db: number; hz: number } };
  };
  themesStereoGate: { corr: boolean; sideMid: boolean; monoLoss: boolean };
}
interface ElevenLabsRecord {
  source: string;
  /** Release 39.5: cues added beside `cues` (they replace no file); pinned by `audio-chapter-select-alternates.test.ts`. */
  alternates?: { cue: string; after: { bytes: number } }[];
  gates: { qaStrictFindings: number };
  stereoGate: { thresholds: { corr: [number, number]; sideMid: [number, number]; monoLossMin: number } };
  cues: Cue[];
}
interface ManifestEntry extends EntryFields {
  file: string;
  score?: string;
  source?: string;
}

const record = read('docs/audio/music-elevenlabs-2026-10-07.json') as ElevenLabsRecord;
const manifest = read('public/audio/manifest.json') as {
  music: Record<string, ManifestEntry>;
  sfx: { bytes: number } | null;
  sfxV2: { bytes: number } | null;
};
const v2 = read('docs/audio/music-v2-2026-09-30.json') as {
  totals: { musicBytesAfter: number };
  cues: { cue: string; after: { bytes: number; sha256: string }; loop: { loopStart: number; loopEnd: number; duration: number } }[];
};
const o1 = read('docs/audio/music-o1-2026-09-30.json') as { cues: { cue: string; after: { bytes: number } }[] };

const RATE = 44100;
const RUN_ON_SECONDS = 3;
const sha256 = (cue: string) =>
  createHash('sha256').update(readFileSync(new URL(`../../public/audio/music/${cue}.mp3`, import.meta.url))).digest('hex');
const inRange = (x: number, [low, high]: [number, number]) => x >= low && x <= high;

/** The "How each cue ships" table in THEMES.md: cue -> its cells. */
function themesRow(cue: string): string[] | null {
  const line = text('docs/audio/THEMES.md')
    .split(/\r?\n/)
    .find((l) => l.startsWith(`| \`${cue}\` | `));
  return line ? line.split('|').slice(1, -1).map((c) => c.trim()) : null;
}

describe('ElevenLabs music: the record', () => {
  it('lists each cue once, in order, and every one is a cue the game plays and can still synthesise', () => {
    const names = record.cues.map((c) => c.cue);
    expect(names).toEqual([...new Set(names)].sort());
    for (const cue of names) {
      expect(manifest.music[cue], `${cue} is not in the manifest`).toBeDefined();
      expect(hasTrack(cue), `${cue} has no score to fall back on`).toBe(true);
    }
  });

  it('is exactly the set of manifest entries that exempt themselves from the stale-render checks', () => {
    const exempt = Object.entries(manifest.music)
      .filter(([, entry]) => externalSource(entry) !== null)
      .map(([name]) => name)
      .sort();
    expect(exempt).toEqual([...record.cues.map((c) => c.cue), ...(record.alternates ?? []).map((c) => c.cue)].sort());
    for (const name of exempt) expect(manifest.music[name]!.source, name).toBe(record.source);
  });
});

describe.each(record.cues.map((c) => [c.cue, c] as const))('ElevenLabs music: %s', (cue, c) => {
  const entry = manifest.music[cue]!;
  const installed = c.installedVariant === null ? undefined : c.variants[c.installedVariant];

  it('ships the file the record measured, byte for byte, and says which variant it is', () => {
    expect(installed, `${cue}: installedVariant ${c.installedVariant} is not a variant in the record`).toBeDefined();
    expect(readFileSync(new URL(`../../public/audio/${entry.file}`, import.meta.url)).length).toBe(c.after.bytes);
    expect(sha256(cue)).toBe(c.after.sha256);
    expect(c.after.sha256, 'the installed file is the staged variant it says it is').toBe(installed!.sha256);
    expect(entry.file).toBe(`music/${cue}.mp3`);
  });

  it('has the manifest entry its variant describes, and no score fingerprint', () => {
    const { loopStart, loopEnd, duration, bytes, lufs, truePeakDb } = entry;
    expect({ loopStart, loopEnd, duration, bytes, lufs, truePeakDb }).toEqual(installed!.manifestEntry);
    expect(entry.bytes).toBe(c.after.bytes);
    // Exactly these keys: a fingerprint of a score it is not a render of would be a lie, and `source` is the exemption.
    expect(Object.keys(entry).sort()).toEqual(['bytes', 'duration', 'file', 'loopEnd', 'loopStart', 'lufs', 'source', 'truePeakDb']);
  });

  it('can be swapped to any variant it lists: each variant\'s manifest entry is the size of its own file', () => {
    for (const [name, v] of Object.entries(c.variants)) expect(v.manifestEntry.bytes, `${cue} ${name}`).toBe(v.bytes);
  });

  it('decodes to the length the manifest says, with the 3 s run-on past the loop end', () => {
    expect(Math.abs(c.after.decodedSamples - Math.round(entry.duration * RATE)), 'the manifest keeps 4 decimals').toBeLessThanOrEqual(2);
    expect(Math.abs(entry.duration - (entry.loopEnd + RUN_ON_SECONDS))).toBeLessThan(0.001);
  });

  it('replaced the file the earlier record pinned', () => {
    const wasV2 = v2.cues.find((x) => x.cue === cue);
    const wasO1 = o1.cues.find((x) => x.cue === cue);
    if (wasV2) {
      expect([c.before.bytes, c.before.sha256]).toEqual([wasV2.after.bytes, wasV2.after.sha256]);
      const { loopStart, loopEnd, duration } = c.before.manifestEntry;
      expect([loopStart, loopEnd, duration]).toEqual([wasV2.loop.loopStart, wasV2.loop.loopEnd, wasV2.loop.duration]);
    } else {
      expect(wasO1, `${cue} is in neither earlier record`).toBeDefined();
      expect(c.before.bytes).toBe(wasO1!.after.bytes);
    }
    expect(c.before.manifestEntry.bytes).toBe(c.before.bytes);
    expect(c.before.manifestEntry.file).toBe(`music/${cue}.mp3`);
  });

  it('passed the qa.mjs gates, the loudness target and the true-peak ceiling', () => {
    expect(c.after.qa.failures).toEqual([]);
    expect(c.after.qa.seamOk).toBe(true);
    expect(Math.abs(c.after.qa.lufs + 16), 'LUFS').toBeLessThan(0.5);
    expect(c.after.qa.truePeakDb, 'true peak').toBeLessThanOrEqual(-1);
  });

  it('discloses the stereo gate as measured, and keeps a variant that passes it', () => {
    const t = record.stereoGate.thresholds;
    const m = c.after.measure;
    expect(c.themesStereoGate).toEqual({
      corr: inRange(m.corr, t.corr),
      sideMid: inRange(m.sideMid, t.sideMid),
      monoLoss: m.monoLoss >= t.monoLossMin,
    });
    expect({ corr: m.corr, sideMid: m.sideMid, monoLoss: m.monoLoss }, 'the measured file is its variant').toEqual(installed!.stereo);
    const narrow = c.variants['narrow'];
    expect(narrow, `${cue}: no gate-passing variant to swap to`).toBeDefined();
    expect(inRange(narrow!.stereo.corr, t.corr) && inRange(narrow!.stereo.sideMid, t.sideMid) && narrow!.stereo.monoLoss >= t.monoLossMin).toBe(true);
  });

  it('is described by THEMES.md and CREDITS.md the way the record has it', () => {
    const row = themesRow(cue);
    expect(row, `THEMES.md "How each cue ships" has no row for ${cue}`).not.toBeNull();
    const [, game, shipsAs, corr, sideMid, monoLoss] = row!;
    expect(game).toBe(c.game);
    expect(shipsAs).toMatch(/ElevenLabs/);
    expect([Number(corr), Number(sideMid), Number(monoLoss)]).toEqual([c.after.measure.corr, c.after.measure.sideMid, c.after.measure.monoLoss]);
    if (Object.values(c.themesStereoGate).some((ok) => !ok)) expect(shipsAs, `${cue}: the failed stereo gate is not disclosed`).toMatch(/stereo gate/i);

    const credits = text('docs/audio/CREDITS.md');
    expect(credits, `CREDITS.md does not name the brief ${c.brief}`).toContain(c.brief);
    expect(credits, `CREDITS.md does not carry the raw take's hash for ${cue}`).toContain(c.raw.sha256);
    // The prompt is the credit: it is what makes the piece ours. A text prompt must be there exactly as sent.
    if (typeof c.request.prompt === 'string') expect(credits, `CREDITS.md does not carry the prompt of ${cue} as sent`).toContain(c.request.prompt);
    // A composition plan is the same thing in sections: each one, as sent, on a line of its own.
    for (const [i, chunk] of (c.request.composition_plan?.chunks ?? []).entries()) {
      expect(credits, `CREDITS.md does not carry section ${i + 1} of the plan of ${cue} as sent`).toContain(JSON.stringify(chunk));
    }
  });
});

describe('ElevenLabs music: the whole', () => {
  it('moved the music total by exactly the bytes these cues changed, from the total music v2 pinned', () => {
    const total = Object.values(manifest.music).reduce((sum, e) => sum + e.bytes, 0);
    const moved = record.cues.reduce((sum, c) => sum + c.after.bytes - c.before.bytes, 0) + (record.alternates ?? []).reduce((sum, c) => sum + c.after.bytes, 0);
    expect(total).toBe(v2.totals.musicBytesAfter + moved);
  });

  it('is inside the shipping budget with the sfx sprites counted, and qa.mjs found nothing', () => {
    const shipped =
      Object.values(manifest.music).reduce((sum, e) => sum + e.bytes, 0) + (manifest.sfx?.bytes ?? 0) + (manifest.sfxV2?.bytes ?? 0);
    expect(shipped).toBeLessThan(AUDIO_BUDGET_BYTES);
    expect(record.gates.qaStrictFindings).toBe(0);
  });

  it('uses the stereo gate thresholds the remaster tool uses', () => {
    const source = text('tools/audio/remaster-score.mjs');
    const found = /corr: \[([\d.]+), ([\d.]+)\],\s*sideMid: \[(-?\d+), (-?\d+)\],\s*monoLossMin: (-?[\d.]+)/.exec(source);
    expect(found, 'GATES in remaster-score.mjs changed shape').not.toBeNull();
    const [, c0, c1, s0, s1, mono] = found!;
    expect(record.stereoGate.thresholds).toEqual({ corr: [Number(c0), Number(c1)], sideMid: [Number(s0), Number(s1)], monoLossMin: Number(mono) });
  });
});
